### ISSUE TITLE
change log is out of date

### ISSUE THREAD

**Issue by ChipDale66** [liprec/azurebi-docs#100]
is the change log page being maintained? It has not been updated since 2017!

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=0fc4a6ae-6c59-4896-b0ac-b69954bf8663
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/box-and-whisker-changelog.html

**Comment by liprec** [comment]
Hi @ChipDale66 ,

Thanks for pointing this out te me. Somehow I have missed to update the changelog.
I will update it soon.

-JP
