### ISSUE TITLE
Pass Slicer Expansion Levels 

### ISSUE THREAD

**Issue by Andykay-12** [liprec/azurebi-docs#101]
*Start issue here*
If you have a Slicer on Page 1 and have expanded the selections and have made specific selections, when you go to Page 2, that has the same Slicer on it, while the checkbox is checked, the Slicer on Page 2 shows the LAST expansion lever IT displayed and not the expansion Level from the slicer on the Page you were just at.

If you're able to pass the selected values...Shouldn't the expansion level also be passed?

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @Andykay-12 ,

Thanks for your feedback. Unfortunately the sync slicer feature in Power Bi only syncs the current selection state between the slicers. Power BI doesn't support syncing the expand/collapse state.

-JP

**Comment by Andykay-12** [comment]
So if you COPY the slicer and place it on another page...They won't communicate their settings when you switch from one page to another?
Also, I tried your barchart app...Doesn't work with PowerBI PRO,Jan2019.


    On Saturday, May 9, 2020, 11:25:53 AM GMT+2, Jan Pieter Posthuma <notifications@github.com> wrote:  
 
 


Hi @Andykay-12 ,

Thanks for your feedback. Unfortunately the sync slicer feature in Power Bi only syncs the current selection state between the slicers. Power BI doesn't support syncing the expand/collapse state.

-JP

**Comment by liprec** [comment]
The sync slicer option in Power BI only syncs the selection state of slicer between pages.
And if you copy a visual from one page to an other Power BI should also copy the metadata (e.g. formatting and fields) to the other page(s).
But after that they are two different visuals that doesn't communicate with each other.
