### ISSUE TITLE
D3.js visual certification request

### ISSUE THREAD

**Issue by XhaheerKhan** [liprec/azurebi-docs#103]
*Start issue here*

Hi Jan Pieter Posthuma  Kindly certify the D3,js visual so that we can use it after the latest power BI update 
Regards
Shaheer Ahmed Khan
professional service consultant 
Convergent Business Technologies
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=2380fb48-08d2-44bc-aaa2-2decb8eeed18
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/index.html

**Comment by liprec** [comment]
See comment #104.
