### ISSUE TITLE
D3.js Custom Visual Certification Request

### ISSUE THREAD

**Issue by XhaheerKhan** [liprec/azurebi-docs#104]
*Start issue here*

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=59bc6305-3908-4afa-bdfd-66ed39c91192
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/d3js.html

**Comment by XhaheerKhan** [comment]
Hi Jan Pieter Posthuma Kindly certify the Power BI D3.JS. we love the visual and use it in many dashboards. 
Regard 
Shaheer

**Comment by liprec** [comment]
Due to the certification rules it is not possible to certify the Power BI D3js visual: it is not allowed to run 'user code' in any certified viusal.
Sorry.
