### ISSUE TITLE
Property name: EncryptConnection. The exception was raised by the IDbConnection interface

### ISSUE THREAD

**Issue by tushmesh** [liprec/azurebi-docs#108]
*Start issue here*
I am trying to deploy Model.bim using the Azure Analysis Services Deploy task. 
- task: liprec.vsts-release-aas.deploy-aas-db.deploy-aas-db@1
  displayName: 'Deploy model to asazure://****.asazure.windows.net/****'
  inputs:
    ConnectedServiceNameARM: Development
    aasServer: '****'
    modelName: 'Digital_DEVOPS'
    loginType: spn
    tenantId: '***'
    appId: '***'
    appKey: '$(spkey)'
    pathToModel: 'Model.bim'
    connectionType: sql
    sourceSQLServer: ***.database.windows.net
    sourceSQLDatabase: ***
    sourceSQLUsername: '$(userid)'
    sourceSQLPassword: '$(passwordid)'
Gets the below **Error** while performing "Process Database" as full.

_Failed to save modifications to the server. Error returned: 'The given credential contains a property with a null value. Data source kind: SQL.  Property name: EncryptConnection. The exception was raised by the IDbConnection interface._
Snippet from the Database script
"credential": {
              "AuthenticationKind": "OAuth2",
              "kind": "SQL",
              "path": "***.database.windows.net",
              "Username": "xyz",
              "EncryptConnection": null
            }

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=4381b0c0-3a30-42ba-ad70-47e99b1994e1
* document_url=https://azurebi-docs.jppp.org/vsts-extensions/azure-analysis-service-deploy.html

**Comment by liprec** [comment]
Currently the task only support database authentication for the SQL database connection.
It looks like your connection is using AD/OAuth2 for authentication and that is not (yet) supported with this task.
