### ISSUE TITLE
Resolution on the slicer

### ISSUE THREAD

**Issue by GitHubUserNameWm** [liprec/azurebi-docs#109]
Hello, 

We noticed that sometimes **resolution on the slicer** is not good when using the slicer:

![image](https://user-images.githubusercontent.com/55703662/85722363-82249d80-b6f2-11ea-95c5-06b22d3473bc.png)

Do you have any intention or possibility to improve this ?

Thank you,
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Thanks for your feedback. Unfortunately I have no idea what is causing this, but in the upcoming update there has been some changes in how the slicer is being drawn, so I hope that this will solve this issue.

**Comment by GitHubUserNameWm** [comment]
Thank you for your answer and your work.
I will wait for the next update.
