### ISSUE TITLE
Hierarchy slicer appear blank in Firefox

### ISSUE THREAD

**Issue by dfacto-ju** [liprec/azurebi-docs#112]
The hierarchy slicer appear blank for all reports in PowerBI RS with Firefox.
With IE, CHrome, EDGE, it's functionnal.

How fix this issue?

Thanks

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Have you updated to the latest patch level of the Power BI Report Server?

**Comment by dfacto-ju** [comment]
We are in PowerBI RS may 2020 version : 15.0.1103.227

**Comment by liprec** [comment]
If I look at https://docs.microsoft.com/en-us/power-bi/report-server/changelog I see there are some more recent updates,, so my advise is to update to the latest patch level are there were some issues in the custom visual area.

**Comment by dfacto-ju** [comment]
Ok thank you, we will try to install the more recent updates.

**Comment by dfacto-ju** [comment]
After upgrade in Version: 1.8.7485.35104.
The problem is still here.

**Comment by liprec** [comment]
To bad. Best suggestion is to report a support case as it looks to me that it is something related to Firefox and Power BI as chromium browsers are working.

**Comment by bravespiano5** [comment]
Folks on my team are having similar issues with FF...the visual is completely missing.

**Comment by loyso1** [comment]
Same issue in FF on 1.8.7485.35104
