### ISSUE TITLE
Hierarchy slicer doesn't work anymore

### ISSUE THREAD

**Issue by mariusmueller1983** [liprec/azurebi-docs#113]
*Start issue here*
Hello,

we are using the current version (2.1.1 even if we can't see them in the release notes) of the Hierarchy slicer in some of our Power BI reports. We were informed on Tuesday 30.06.2020 that the slicer no longer works. The symptom is, if you click on an Element in the tree, which has child nodes you see a loading bar, but nothing is displayed, even if you wait (see also screen attached).
![Hierarchy_Control_issue](https://user-images.githubusercontent.com/67729352/86325938-3d908900-bc41-11ea-894c-d5a35d577f71.png)

We got also the info from our Implementation partner, that they are facing the same problem for other customers.

update 202007021402: As type of source we are using Microsoft Dynamics CRM Online with the OData connector (oAuth2 authentication).
To be even more precise we visualize data from the table (entity) systemuser. In this table there is a field called manager, where you can build up an hierarchy between systemuser records.

We were actually very happy with the hierarchy slicer and would not like to use a different solution.

Thank you very much!

BR,

Marius Müller

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
Thanks for the feedback and indeed the documentation/changelog is not yet updated.
But regarding your issue: can you share a bit more details of the configuration you are using? Type of source?

**Comment by mariusmueller1983** [comment]
> Thanks for the feedback and indeed the documentation/changelog is not yet updated.
> But regarding your issue: can you share a bit more details of the configuration you are using? Type of source?

Hello liprec,

As type of source we are using Microsoft Dynamics CRM Online with the OData connector (oAuth2 authentication).
To be more precise we visualize data from the table (entity) systemuser. In this table there is a field called manager, where you can build up an hierarchy between systemuser records. Is this info sufficient for you? Thank you very much

BR,

Marius

**Comment by liprec** [comment]
Thanks for the information. Main thing is that you import the data to Power BI (due to some non-supported scenarios with multi-dimensional sources).
Does the issue still exists if you recreate the hierarchy from scratch? And if not, is it possible to share a (anonymized) sample with me so I can look into it more in depth? You can send it to mail@datascenarios.nl.

**Comment by mariusmueller1983** [comment]
> Thanks for the information. Main thing is that you import the data to Power BI (due to some non-supported scenarios with multi-dimensional sources).
> Does the issue still exists if you recreate the hierarchy from scratch? And if not, is it possible to share a (anonymized) sample with me so I can look into it more in depth? You can send it to [mail@datascenarios.nl](mailto:mail@datascenarios.nl).

Thank you for your answer, I already forwarded your question and request for sample data to our Power BI Implementation partner. They should then contact the email address you have provided.

**Comment by foxy-ni** [comment]
Hey Guys,

Having the same issue my side. Hierarchy stopped working. Have tried direct connection to SQL and import mode.

It shows the expand icon but when I click on a level it just spins and seems to fail.

Any help much appreciated! Was really happy with this visual before.

**Comment by liprec** [comment]
Hi @foxy-ni,

Thanks to @mariusmueller1983 I have identified a bug [#126](https://github.com/liprec/powerbi-hierarchySlicer/issues/126) that expanding is not working when the label has a comma (,).
Is this also the case for you? If so, the only workaround for now is to replace the ',' in the label.

Sorry for the inconvenience.

**Comment by dwoolcott** [comment]
We are also having this issue.  All of our data that is being used has a comma in it as it is "Lastname, FirstName"  Replacing them is not an ideal option, is there an option to roll back the deployment or when can we expect a bug fix?

**Comment by mariusmueller1983** [comment]
> Hi @foxy-ni,
> 
> Thanks to @mariusmueller1983 I have identified a bug [#126](https://github.com/liprec/powerbi-hierarchySlicer/issues/126) that expanding is not working when the label has a comma (,).
> Is this also the case for you? If so, the only workaround for now is to replace the ',' in the label.
> 
> Sorry for the inconvenience.

Hello Jan Pieter,

thank you very much for your analysis and workaround suggestion, nevertheless can you specify a time frame for when the problem will be fixed?

Thank you very much!

BR,

Marius

**Comment by liprec** [comment]
Hi All,

Sorry for this inconvenience: it is a bug that reoccurred and slipped thru the (regression)tests. Fix is almost ready, but I am dependent of the review cycle of Microsoft.

-JP

**Comment by liprec** [comment]
Solved with the v2.1.3 release
