### ISSUE TITLE
Power BI Visual  Name: Hierarchy Slicer   Problems

### ISSUE THREAD

**Issue by JonhSilver** [liprec/azurebi-docs#114]
1. How can be wrong version  here https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html?tabs=docs-open  and in Power BI  Id: HierarchySlicer1458836712039  Version: 2.1.1  ?
2. Other issue https://community.powerbi.com/t5/Desktop/All-formats-lost/m-p/1193934 and https://community.powerbi.com/t5/Issues/data-slicer-formats-gone-in-all-projects-after-2020-06-28/idi-p/1191092

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=2380fb48-08d2-44bc-aaa2-2decb8eeed18
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/index.html

**Comment by liprec** [comment]
Thanks for your feedback and I just updated the documentation.

And see for the other issue the Power BI Community thread.

-JP
