### ISSUE TITLE
Hierarchy Slicer is clearing the multi selections

### ISSUE THREAD

**Issue by Bart-Lens** [liprec/azurebi-docs#116]
When we multi-select in the hierarchy slicer without waiting to refresh he clears this selection.
When we select, wait, select, wait,... then it works but this is difficult to explain to our end users to work like this

Update : the selection/result is ok but the visual is clearing the ticking box. It appears nothing is selected.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
Hi @Bart-Lens,

Is it possible to share a PBIX file? You can send it to mail@datascenarios.nl and then I can take a look.

-JP

**Comment by Bart-Lens** [comment]
not really. Sorry. Does this mean you can't reproduce this? That we are the only ones having this issue?

**Comment by liprec** [comment]
Currently I am not aware of any issues with the multi-select option and I cannot reproduce the issues indeed.
So my assumption is that there could be an issue with my slicer and your data.
I am also ok if you can create a sample with the issue and dummy data and share that with me.

**Comment by wwisse** [comment]
I have this problem too. It's worse: I sometimes can't Multi-select, when I try it selects all. In one report it DOES work perfectly on one page but not on another page that works exactly the same way.  I suspect it started with the new version 2.1.1. 

Good result on one page:
![image](https://user-images.githubusercontent.com/68054533/87019699-3504f900-c1d3-11ea-896f-1b38b4afd313.png)

Bad result on another page:
![image](https://user-images.githubusercontent.com/68054533/87020031-9b8a1700-c1d3-11ea-8660-1054cd6e19cc.png)

This also happens when I do the selection very slowly.

I hope you  can help.

Thanks,

WW

**Comment by liprec** [comment]
HI @wwisse,

Is it possible to share the report so I can take a look?
You can send it to mail@datascenarios.nl. And no problem if you replace the data with sample data.

-JP

**Comment by wwisse** [comment]
Beste JPP,

Zijn er al andere klachten binnengekomen hierover? Ik heb een vermoeden dat het iets met performance te maken heeft. Mijn rapporten waarbij dit speelt hebben grote datasets en laden traag.
Hope this helps. En dat je Nederlands kan- oeps!

Vriendelijke groet,
Wiep

Van: Jan Pieter Posthuma <notifications@github.com>
Verzonden: donderdag 9 juli 2020 11:13
Aan: liprec/azurebi-docs <azurebi-docs@noreply.github.com>
CC: Wiep Wissema <wwissema@zorgned.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [liprec/azurebi-docs] Hierarchy Slicer is clearing the multi selections (#116)


HI @wwisse<https://github.com/wwisse>,

Is it possible to share the report so I can take a look?
You can send it to mail@datascenarios.nl<mailto:mail@datascenarios.nl>. And no problem if you replace the data with sample data.

-JP

**Comment by liprec** [comment]
Hi @wwisse,

The current version works a bit different than the previous versions: the visual is not waiting for the callback to visualize the selection. But this should not have any impact on the selection as the latest selection is pushed to Power BI, but I can imagine that there could appear a 'race condition' and probably you are hitting one.
Looks to me that this is a rare situation, but I will monitor if there are more people are facing this situation.

-JP

PS. Excuse my answer in English, but probably there could be more people could face this situation.

**Comment by wwisse** [comment]
Hi JP,

This problem is still occuring a lot. I am resorting to using the standard slicer in PowerBI. It works very well but I miss the Value-field... 
Any news? 

Best regards,

Wiep
