### ISSUE TITLE
Contents are not loaded in Fireforx

### ISSUE THREAD

**Issue by gis2kor** [liprec/azurebi-docs#118]
Hello

Hierarchy contents are not getting loaded in the Firefox browser.
We are using 68.9.0esr (32-bit)
Request you look into this issue

Thank you

Best Regards.
Girish 

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
Hi @gis2kor,

Looks like there is an issue with Firefox, Power BI and my visual. Problem is that it is working correctly with Chrome, so to me it looks like there is more a general issue.
My advice is to raise a support ticket with Microsoft to see what is really happening.

-JP

**Comment by liprec** [comment]
Closed in favor to #112
