### ISSUE TITLE
Can i see the coding for Hierarchical Slicer? Please 

### ISSUE THREAD

**Issue by navjotdeol** [liprec/azurebi-docs#120]
*Start issue here*

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
If you are looking for the code of the HierarchySlicer, see https://github.com/liprec/powerbi-hierarchySlicer
