### ISSUE TITLE
Hierarchy visual breaks if string values have a comma in them

### ISSUE THREAD

**Issue by misnermedtronic** [liprec/azurebi-docs#121]
I believe this is a newly-introduced bug (possibly within the last week or 2), either by a Power BI update, or a Hierarchy Slicer update.

Reproduced easily in Excel. Introduce a comma into a node with children. (Like the very common usage for an Org hierarchy of LastName, FirstName). You can no longer expand that node - behavior is a very small spinning icon where the triangle once was, which then times out and shows the "down" triangle, but no children. Examples below using all default settings in an empty report.

Data set 1: works fine
![image](https://user-images.githubusercontent.com/68130343/87205355-e176d600-c2cc-11ea-893f-122ee3aa154c.png)

Data set 2: Broken by adding a comma to "Tree 2" (changed to "Tree, 2"), spinning
![image](https://user-images.githubusercontent.com/68130343/87205558-59dd9700-c2cd-11ea-8fc7-173daca0beaa.png)

Final state - "expanded" arrow is shown, but children records are not shown:
![image](https://user-images.githubusercontent.com/68130343/87205705-aaed8b00-c2cd-11ea-8f1f-eb03c832ca44.png)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
See liprec/powerbi-hierarchySlicer#126 for more info: fix is coming.
