### ISSUE TITLE
Interact with D3.js visuals?

### ISSUE THREAD

**Issue by Calspencer01** [liprec/azurebi-docs#123]
I am wondering if it is possible to interact with the D3 visualizations using D3 UI, such as mouseover, mouseout, d3.brush(). From what I've tried it seems like the only thing the user can click on is the entire visualization, not the individual data points. Is there a way to create this interactivity?
Thank you!

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=59bc6305-3908-4afa-bdfd-66ed39c91192
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/d3js.html

**Comment by liprec** [comment]
Hi @Calspencer01,

The normal interaction with a D3js visual should be working. If you take a look at page 3 of my showcase (https://azurebi-docs.jppp.org/powerbi-visuals/d3js.html) you will see that with a click of the mouse the nodes can be expanded/collapsed.
The code used in the visual is based on this sample: https://bl.ocks.org/mbostock/4339083

-JP

**Comment by Calspencer01** [comment]
Ah, I figured it out. Thank you very much, this will come in handy!

Best wishes,
Calvin
