### ISSUE TITLE
visualize sample size

### ISSUE THREAD

**Issue by superuser-27** [liprec/azurebi-docs#126]
*Start issue here*
Hello, it would be nice to have the option to display the sample size directly somewhere on the plot, instead of having to hover with the mouse over each bar. Thank you for making this great visualization tool!

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=4555c56c-3a13-42d3-a4d4-df34d7b4e455
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/box-and-whisker-chart.html

**Comment by mef47** [comment]
Yes please! I was just about to add this as a suggestion
