### ISSUE TITLE
Certify D3.js visual?

### ISSUE THREAD

**Issue by klassej** [liprec/azurebi-docs#13]
*Start issue here*
Hi, would it be possible for you to certify the Power BI D3.js Visual? Want to use it in a corporate environment.

https://docs.microsoft.com/en-us/power-bi/power-bi-custom-visuals-certified

Thanks

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=59bc6305-3908-4afa-bdfd-66ed39c91192
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/d3js.html

**Comment by klassej** [comment]
Hi, any news on this?

Thanks

**Comment by liprec** [comment]
Now that the certified requirements have changed (https://docs.microsoft.com/en-us/power-bi/power-bi-custom-visuals-certified#certification-requirements) it is not possible to certify this kind of visual, unfortunately.

> * Source Code requirements:
> ...
>    * Ensure no arbitrary/dynamic code is run (bad: eval(), unsafe to use of settimeout(), requestAnimationFrame(), setinterval(some function with user input), running user input/data)
