### ISSUE TITLE
Text inside Hierarchy slicer gets blurry when it exceeds the size of the slicer

### ISSUE THREAD

**Issue by timeeek** [liprec/azurebi-docs#130]
Hello,

I've recently noticed that when using the hierarchy slicer the text is perfectly fine as long as i dont extend my hierarchy (or extend it only far enough so the amount of text is still smaller than the size of the box). Once i use the "expand all" button for example the text gets a bit blurry. If i collapse the hierarchy its fine again. Its a small thing but kind of annoying at the same time. Maybe this is an easy fix. Thanks!
![image](https://user-images.githubusercontent.com/70568684/91822964-d12e0800-ec38-11ea-9391-3f17e068820b.png)
![image](https://user-images.githubusercontent.com/70568684/91822902-b9568400-ec38-11ea-9a02-6197e3f6f702.png)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by TallArnie** [comment]
I noticed exactly the same issue.
