### ISSUE TITLE
Scroll down issue in version 2.1.4.0

### ISSUE THREAD

**Issue by mohnishbhagde** [liprec/azurebi-docs#131]
*Start issue here*

https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104380820?tab=Reviews
HierarchySlicer - version 2.1.4.0

The issue with version 2.1.3 related to scroll bar is present in version 2.1.4.0 too. Please help.

We found a bug when filtering with the HierarchySlicer visualization: the scroll bar does not show all results towards the end/bottom.

You can reproduce this issue with any source data by:
Select the HierarchySlicer visual
Add up to 3 hierarchical levels with several values for each level
Keep the visualization box small
Try to scroll down to find any value. 

Can you please check this issue?

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by adamsink** [comment]
Hello,

    This is a perfect tool for our needs, however, I too am suffering the same issue.  Scroll bar seems to "stick" when nearing the end of the list and you never see the last few entries.  

Thank you for your work.

**Comment by liprec** [comment]
Thanks for the bug report and indeed I can confirm that this is unfortunately a bug and will be fixed in the next version.

-JP

**Comment by bravespiano5** [comment]
Glad to hear a fix is coming soon!

**Comment by SamuelEddy** [comment]
Hi @liprec, thanks for supporting this excellent slicer. We have the same issue and are eagerly awaiting this fix. Do you have an estimate when it'll be ready?

**Comment by liprec** [comment]
Currently I do not have a timeline yet: the visual is in the process of being (re)certified and after that step it will take 1-2 weeks before it will be general available.

**Comment by SamuelEddy** [comment]
Hey @liprec, has this fix been released? I notice it's been recertified. Thanks

**Comment by liprec** [comment]
Yes, the version currently available (v2.2.1) has the fix for the scrolling issue.
