### ISSUE TITLE
Selected options do not show as selected after selecting a different slicer value.

### ISSUE THREAD

**Issue by jm7387** [liprec/azurebi-docs#138]
I have a report that has version 2.2.2 of the Hierarchy Slicer and another standard slicer configured (e.g, Region). After selecting a Hierarchy Slicer option and then a value from the Region slicer, the Hierarchy Slicer has all checkboxes cleared even though the selected values do persist. This happens in Edge, FireFox, and the Power BI iOS mobile app.

Any help or response will be much appreciated. 
Regards!  

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Thanks for your feedback and I will take a look at the issue.
Is it possible to share a sample PBIX file with the described behavior with me?

Thanks, JP

**Comment by jm7387** [comment]
I tried duplicating this with a small subset of generic data in an Excel workbook and was unable to duplicate. The Hierarchy Slicer is used for filtering an organization structure that is 7 levels. A dimension Hierarchy was created for Levels 2 through Level 7 and then that Hierarchy was used for the Fields of the Hierarchy Slicer – this is where I experienced the slicer checkboxes not being selected after selecting a value from a different slicer.

Replacing the dimension hierarchy in the Fields list though with the individual attributes (Level 2, Level 3, Level 4, Level 5, Level 6, Level 7) works as expected. As time allows, I’ll try to get a more generic dataset and try to duplicate. For now, though, this is working without issue (after replacing the hierarchy in the Fields with the individual attributes).

Thank you much for your prompt response. Much appreciated! Please consider this issue as closed for now.
