### ISSUE TITLE
Hi，I got a note from the visual named hierarchySlicer when I was working on PBI desktop, the note said that the visual hierarchySlicer will be disused soon after and I should find another Slicer to replace the hierarchy Slicer. is the note real? and when is the deadline? hope your response, Thanks！

### ISSUE THREAD

**Issue by ddwu-glitch** [liprec/azurebi-docs#140]
*Start issue here*

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by ddwu-glitch** [comment]
The visual id is HierarchySlicer1458836712039，and the version is 2.2.2

**Comment by liprec** [comment]
I am not aware of any of this kind of messages. Do you use the latest version of the slicer and Power BI Desktop (December 2020)?

**Comment by ddwu-glitch** [comment]
> I am not aware of any of this kind of messages. Do you use the latest version of the slicer and Power BI Desktop (December 2020)?

I Can see the version is 2.2.2. the note said the interface of the visual is old and will be unsupported.

**Comment by liprec** [comment]
Can you share a screenshot of that message? And also what version of Power BI desktop are you using?

**Comment by ddwu-glitch** [comment]
> Can you share a screenshot of that message? And also what version of Power BI desktop are you using?

the Screenshot is in Chinese...I had described which it said with English in last message. PBI desktop version:2.81.5831.1181 64-bit (May 2020)
![hierarchySlicer将遭弃用](https://user-images.githubusercontent.com/77428610/104582687-2a07b580-569b-11eb-8794-5fb94d2a8eb1.png)

**Comment by liprec** [comment]
Thanks for the screenshot. There could be an option that triggers the message is to the fact that you are using in Power BI terms an old version. Is it possible to try to open the report in the latest version of Power BI desktop (December 2020) to see if the message still appears?

**Comment by ddwu-glitch** [comment]
Thanks for your idea, I can't change my version May to December, because it should be matched with Report Server May. A good news is I have not see the note again . Thanks for your help

**Comment by liprec** [comment]
Good to hear that the notice has disappeared!
