### ISSUE TITLE
Sorting of month name

### ISSUE THREAD

**Issue by RobvanB** [liprec/azurebi-docs#141]
For some reason it does not sort the months properly, even through I've specifically sorted the table by date.
Doesn't matter if I add the levels one-by-one, or as a PowerBi Hierarchy

![image](https://user-images.githubusercontent.com/118380/104954859-1f993480-5997-11eb-9847-6c2147513aae.png)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Did you create the hierarchy yourself? And did you use the 'Sort by column' option to sort the `MONTHNAME` column by a month number?

**Comment by RobvanB** [comment]
I did create the hierarchy myself.
I don't have a month-number to sort by. I do have that field, but does that mean I need to add it to the hierarchy?

![image](https://user-images.githubusercontent.com/118380/105503085-27f1b800-5c94-11eb-9a34-8a4bd6313386.png)

**Comment by liprec** [comment]
If you do not provide an alternative sort column Power BI will sort that columns alphabetically and that is why you see Feb, Jan, Mar. If you use the 'Sort by column' option in Power BI you can sort a column using the sort order of another column. So for a month name column it is common to use the month number as the sorting order: see https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column#sort-using-the-sort-by-column-button for more information on how to use it.
