### ISSUE TITLE
Querying latest run - lastUpdatedAfter?

### ISSUE THREAD

**Issue by chrisbilsoe** [liprec/azurebi-docs#142]
I truly appreciate this new function to query data factory runs as a release gate in DevOps. However I have an issue with getting the last run status: in our senario we run a pipeline after a deployment and need this to succeed before continuing. However the result we are getting is "failed" which is true for the first run earlier that day...
I'm wondering if we need to include "lastUpdatedAfter" in order to query only the latest run of the data factory? And if so shouldn't this be dynamic, so it would be possible to evaluate NOW()?

Thanks in advance

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=97f8e9b4-e14a-417f-b873-1e5efbfa9e82
* document_url=https://azurebi-docs.jppp.org/vsts-extensions/azure-data-factory-query.html

**Comment by liprec** [comment]
Thanks for the feedback and you can indeed include the `lastUpdatedAfter` parameter to exclude previous runs.
But due to the fact that a release gate doesn't support dynamic parameters, you should calculate a correct `lastUpdatedAfter` in the pipeline yourself and store it in a variable.

**Comment by chrisbilsoe** [comment]
Thanks for clarifying - I just want to make sure I understand it correctly: if I store the current run time in the pipeline, I can access that variable as part of the evaluation in the gate? Could you provide a link of how to call such a variable in the gate setup?

**Comment by liprec** [comment]
What you can do is add a PowerShell task with the following logic to set a release variable (`lastUpdatedAfter`) to the current date/time in ISO format:
```
$date=$(Get-Date -Format 'yyyy-mm-ddTHH:MM:ss.000Z');
Write-Host "##vso[task.setvariable variable=lastUpdatedAfter]$date"
```

And after that you can use the variable `lastUpdatedAfter` in the gate as `$(lastUpdatedAfter)`

**Comment by chrisbilsoe** [comment]
Hi again, I really appreciate the your support on this and I realise I'm out of my league setting this up.
I manage to setup the release vaiable and using a default value works with the gate. However I've tried setting the PowerShell Script as the last tasks in the first stage, but it doesn't seem to bind to this release value... I'm fairly sure I'm missing some setting, but I can't help feel I'm so so close.  I have look at the online docs but haven't gotten any closer.
Again thanks for your help, I really appreciate it

![image](https://user-images.githubusercontent.com/46591410/105482842-40b89880-5ca9-11eb-9722-cceb2c77cc78.png)

**Comment by liprec** [comment]
You can leave the 'Output variable' part blank, as far as I know. The PowerShell script already sets the variable correctly to the current date/time.

**Comment by chrisbilsoe** [comment]
Hi again. Unfornuatly this still doesn't work... 
If I set the variable to somehting default, it does show up in the Query: 
![image](https://user-images.githubusercontent.com/46591410/106114763-39cdd200-6150-11eb-8aeb-0c2ed2eb37ba.png)
![image](https://user-images.githubusercontent.com/46591410/106114776-3cc8c280-6150-11eb-879a-f102082374de.png)

If I don't set a default value nothing shows up (although the PS code has been run):
![image](https://user-images.githubusercontent.com/46591410/106114911-6eda2480-6150-11eb-91e2-4ee0c7a52dc9.png)
![image](https://user-images.githubusercontent.com/46591410/106114970-82858b00-6150-11eb-9d9e-3465ff32b370.png)

I can't help feel that somehow the link between the PS script and the variable isn't working.
Do you have any ideas here?

**Comment by liprec** [comment]
Hi @chrisbilsoe,

Sorry but finally I took the time to look into this and my original idea was not correct. And luckily there is a (hidden) variable that can be used as `lastUpdatedAfter` to check if there no jobs running at the start of the deployment: `$(Release.Deployment.StartTime)`
So you can drop the PowerShell script and use `$(Release.Deployment.StartTime)` directly as input for the gate.

**Comment by chrisbilsoe** [comment]
Absolutely awesome - it works just as I wanted it to. I think this would be a nice addition to the documentation. Thanks @liprec for your help!
