### ISSUE TITLE
Power BI Box and Whisker not working onpremise server (Januar 2020)

### ISSUE THREAD

**Issue by fleschgordon** [liprec/azurebi-docs#143]
hi,

does the visual in general not work onpremise or we need a newer version of the pbi server ?

thx for any info on this
michael

⚠ Please use the links on the bottom of the [documentation pages](https://azurebi-docs.jppp.org) to get a link between an issue and the page. ⚠

**Comment by liprec** [comment]
Is it possible to upgrade to either the latest version of either January 2020 or October 2020 to see if the problem still occurs?

**Comment by fleschgordon** [comment]
yes we checked that yesterday and the problem still occure with the October 2020 version. Do you know the reason ?

**Comment by liprec** [comment]
No. do not have a reason why this is happening. Is it only happening in the desktop version? Or also in the web version of the report?

**Comment by fleschgordon** [comment]
in deskop its looking good. problem is only in web version

**Comment by liprec** [comment]
Can you make sure that the web version is also updated to the latest version/patch level?

**Comment by fleschgordon** [comment]
i figured it out now. I use a custom authentication provider and i have to place this in the web.config that it worked:
<forms loginUrl="logon.aspx" name="sqlAuthCookie" timeout="60" path="/" **cookieSameSite="None"**>
