### ISSUE TITLE
Hierarchy Slicer which was placed on a bookmark can't show the right items 

### ISSUE THREAD

**Issue by ddwu-glitch** [liprec/azurebi-docs#144]
Hierarchy Slicer which was placed on a bookmark can't show the right items that have been kept in bookmark, when jump from another report page in which the same hierarchy have been added an new item.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=2380fb48-08d2-44bc-aaa2-2decb8eeed18
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/index.html

**Comment by ddwu-glitch** [comment]
An added message: the bookmark is kept with "Data"

**Comment by liprec** [comment]
Did you update the bookmark after setting the report altering the visuals? Looks to me that the bookmark is still linked to set the focus to the other report page with the slicer.
