### ISSUE TITLE
Hierarchy Slicer goes wrong when under single selection

### ISSUE THREAD

**Issue by YuChingC** [liprec/azurebi-docs#145]
When the Slicer is "Single Select", it doesn't retain the filtering value. So when applying the values of other filters, and go back to click on the hierarchy slicer, it refreshes and cleans all the values selected. Under multi select, it works

For example:
1. Create hierarchy slicer for Locations and set as Single Select
2. Create another hierarchy slicer for Shops and set as Multi Select
3. Apply Locations Slicer and select LocationA
4. Apply Shops Slicer and select ShopA, ShopB
5. Click Location Slicer again, and it auto refreshes to select all

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Thanks for the feedback, but is it possible to share a PBIX file with the above behavior?
