### ISSUE TITLE
Force Diagram Problems

### ISSUE THREAD

**Issue by xsg13** [liprec/azurebi-docs#147]
Hi,

Myself and other users have been having an issue where the Force diagram won't render in the tool.  Here is a link with an example from another user:

https://community.powerbi.com/t5/Developer/Network-force-directed-visual-using-power-BI-d3-custom-visual/m-p/645814/thread-id/18820

Do you know what is causing this and if it could be fixed?

Thanks!

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=59bc6305-3908-4afa-bdfd-66ed39c91192
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/d3js.html

**Comment by xsg13** [comment]
Is there any update on this issue?

**Comment by liprec** [comment]
Sorry that I missed your original question, but is it possible to share the PBIX file with me?

**Comment by xsg13** [comment]
Yes, I will provide a version either tomorrow or early next week.

**Comment by xsg13** [comment]
I've attached a zipped version of a simple sample file I created with some generic data.  Thanks!


[Sample Force Directed D3.zip](https://github.com/liprec/azurebi-docs/files/6367457/Sample.Force.Directed.D3.zip)

**Comment by xsg13** [comment]
Is there any update on this issue?  Thanks!

**Comment by xsg13** [comment]
Is there any update on this issue? Thanks!

**Comment by xsg13** [comment]
Is there any update on this issue? Thanks!

**Comment by liprec** [comment]
Hi,

Sorry for the late response, but if you change `pbi.dsv(function(data) {` to the following line including the function to convert the provided dataset
`pbi.dsv(function(d) {return {name:d.name, group:Number(d.group),source:Number(d.source), target:Number(d.target)};}, function(data) {` the force graph start to come alive.

**Comment by xsg13** [comment]
Thank you!  I've got it working now!
