### ISSUE TITLE
Issue with Power BI HierarchySlicer synchronizing

### ISSUE THREAD

**Issue by TimVarlet** [liprec/azurebi-docs#148]
Hi,

I use your HierarchySlicer in my Power Bi reports and it was exactly the slicer I needed, but I encountered a problem : my slicers aren't synchronized between pages with the Power Bi synchronizing feature.
Do you know what is causing this and if it could be fixed?

Thanks ! 

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Thanks for your feedback and currently there is no known issue with the synchronization feature for the Hierarchy Slicer
The only thing that you should be aware is that the all slicers need to have the same levels and in the same order. Or else the selection cannot be synced.

**Comment by TimVarlet** [comment]
Thanks for your answer liprec, both of my slicers were exactly identical and they could not be synced, I tried to copy/paste them and it finally works, thanks a lot !
