### ISSUE TITLE
Password not persisted to final connection string

### ISSUE THREAD

**Issue by YouGitMoreWithLes** [liprec/azurebi-docs#149]
When using this task to deploy, everything deploys normally and seems to work, except that the last parameter, the  sql password is NOT getting saved to the connection string.

- task: liprec.vsts-release-aas.deploy-aas-db.deploy-aas-db@1
  displayName: 'Deploy model to Analysis Services'
  inputs:
    ConnectedServiceNameARM: 'my-ado-azure-connection'
    aasServer: '$(analysis-services-name)'
    modelName: '$(analysis-services-model-name)'
    loginType: spn
    tenantId: '********-****-****-****-************'
    appId: '$(sec-spn-aas-objectid)'
    appKey: '$(sec-spn-aas-secret)'
    pathToModel: '**/Model.bim'
    connectionType: sql
    sourceSQLServer: '$(azure-sql-server-name)'
    sourceSQLDatabase: '$(azure-sql-db-name)'
    sourceSQLUsername: '$(sec-sql-server-admin-user)'
    sourceSQLPassword: '$(sec-sql-server-admin-pwd)'

**Comment by liprec** [comment]
Make sure that you password *does not* contain any quotes (`'`, '"`) as that will result in that a part of the password is used by the script of the task.
