### ISSUE TITLE
Cannot export D3.js as PDF in Power BI Service

### ISSUE THREAD

**Issue by julmoser** [liprec/azurebi-docs#155]
We've successfully used this visual for quite some time now in the Power BI Report Server.
We've since migrated to the Power BI Service and would like to export the reports containing the visual as PDF.
However, the visual is not exported. 
Is exporting not supported?

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=59bc6305-3908-4afa-bdfd-66ed39c91192
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/d3js.html

**Comment by liprec** [comment]
Hi @julmoser,

The export to PDF is indeed not working in the Power BI Service (powerbi.com) due to the fact that the visual is not a certified visual. And due to the nature of the visual, it cannot be certified, so exporting is and will not be supported.

Thanks, JP
