### ISSUE TITLE
Scroll Issue V 2.2.2.0

### ISSUE THREAD

**Issue by kchenail** [liprec/azurebi-docs#156]
Seems this was an issue in the past and was apparently resolved. It appears to have returned.
When item list is long in the slicer, the last few items are out of view and the scroll bar does not go all the way down. As you scroll and hit the bottom, the scroll bar gets smaller and smaller but the bottom items do not move up into view.

Also, when scrolling back up, you need to scroll a certain amount for the scroll bar to regain its full length before the items start to scroll again.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by FrankC-BEL** [comment]
Same issue here with a hierarchy with 7 level 1 and in total a bit more than 100 level 2 entries.
If you open the penultimate level 1 you can endlessly scroll down.  The scroll bar will get smaller and smaller, nevertheless you'll never see the last entry from level 1.

**Comment by matti05** [comment]
@liprec The issue still exists.

**Comment by sergey-do** [comment]
Version: 2.2.2 - the issue behaves exactly as it was initially described https://github.com/liprec/azurebi-docs/issues/156#issue-1000988555
