### ISSUE TITLE
Date selections not appearing in check box / Can't select multiple dates

### ISSUE THREAD

**Issue by tonyYezza** [liprec/azurebi-docs#16]
Issue began on 8/29.

If a field formatted as a date is on any level other that the top, the check box is not appearing when the date is selected.  Additionally, if the slicer is configured to allow multiple selections, it still doesn't allow it.

In the below image you can see the hierarchy, and you can see based on the small image to the left of the slicer that 8/1 is selected.  However, the check box is not appearing.

![image](https://user-images.githubusercontent.com/42872020/44936109-6ee85700-ad41-11e8-9d2d-28df857db713.png)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
Is it possible that your `Lead Month Name` is a date column formatted to as Month Name (`MMMM`) only? I have noticed that those columns are causing issues with how the filter is created.

It is better (for now) to create a column with the month names itself. And you can use the 'Sort By Column' option to get the correct order for the months.

**Comment by tonyYezza** [comment]
Thank you very much the reply.  My Lead Month name is configured exactly as you suggested.  I have a date dimension table with the month name and I sort by the month number.  It's not liking the Lead Date formatted as a date.  If I switch it to text format it will work.  My current work around is to swap out the Lead Date as the bottom level and replace it with the day value alone.  Like this...

![image](https://user-images.githubusercontent.com/42872020/44946130-202fd100-adc4-11e8-9b7e-41a82f8e2e2d.png)

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
