### ISSUE TITLE
Images are not showing up using the d3.js custom visual power bi

### ISSUE THREAD

**Issue by UditJoshi91** [liprec/azurebi-docs#160]
*Start issue here*

This is my code:

var margin = {top: 20, right: 20, bottom: 30, left: 40},
    width = pbi.width - margin.left - margin.right,   // ALTER: Changed fixed width with the 'pbi.width' variable
    height = pbi.height - margin.top - margin.bottom;

var x = d3.scale.ordinal()
    .rangeRoundBands([0, width], 0.1, 0.2);

var y = d3.scale.linear()
    .range([height, 0]);

  
// append the svg object to the body of the page
var svg = d3.select("#chart")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

// ALTER: Replaced the d3.tsv function with the pbi variant: pbi.dsv
    pbi.dsv(type, function(letters) {
    x.domain(letters.map(function(d) { return d.name; }));
    y.domain([0, d3.max(letters,function(d) { return d.rollnumber; })]); 
      
       svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(d3.svg.axis().scale(x).orient("bottom"));

    svg.append("g")
        .attr("class", "y axis")
        .call(d3.svg.axis().scale(y).orient("left"));
    

  
      
 svg.append("g")
   .selectAll(".mypoint")
        .data(letters)
        .enter()
        .append("image")
        .attr("xlink:href", function(d){ return "C:\Users\UditJoshi\Desktop\Onemda ORS\Emojees\Learning.png"})
          .attr("x", function(d){ return d.name })
        .attr("y", function(d){ return d.rollnumber })
        .attr("width", 16)
         .attr("height", 16);
      
});  

function type(d) {
	d.rollnumber= +d.rollnumber;
	return d;
  }
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=b2902cf9-7c1b-4065-bca8-415ff4dd9b6b
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/d3js-changelog.html

**Comment by liprec** [comment]
The custom visual is running, like all custom visuals, in a sandbox and probably that is the reason that it doesn't load the image(s) from your local machine. Can you try with an image that is publicly available from the Internet?
