### ISSUE TITLE
Azure Analysis Service Deployment task - Azure DevOps - deploy model but retain partitions

### ISSUE THREAD

**Issue by aocall1** [liprec/azurebi-docs#161]
In a work project I am using your Azure Analysis Service Deployment task as part of a DevOps release pipeline (https://github.com/liprec/vsts-release-aas)

In the AAS model that is already deployed, many partitions are being created dynamically using Azure Data Factory pipelines that create new partitions every day.

I have noticed that when I deploy the AAS model again using the task in DevOps though, the dynamically created partitions get deleted **if we have not also defined them in the model.bim file**. If we have defined the partition in the file, it remains there after the deployment even including all the data that was previously processed.

Is there anything that I can configure in your task to replicate the "Retain Partitions" behaviour that is available via the AAS deployment wizard? I was looking at this article [https://blog.crossjoin.co.uk/2010/07/23/the-deployment-wizard-and-when-%E2%80%9Cretain-partitions%E2%80%9D-doesn%E2%80%99t-retain-partitions/] and found in the last paragraph the kind of behaviour that I think is what we need:

**"This is why the wizard needs to connect to the target server: it scripts out all the partitions that currently exist on the target and inserts them into the script it generates, instead of just the partitions that are in the .asdatabase file."**

I understand this to mean that existing partitions in the AAS model that was previously deployed can be retained, while new partitions would also be deployed (so basically deploy any partitions defined in the model.bim AND also any existing dynamically created partitions as well).

Any guidance would be appreciated!

Aoife

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=053b7273-7a5f-4aa1-80e7-529cbf4b0b87
* document_url=https://azurebi-docs.jppp.org/index.html

**Comment by liprec** [comment]
The Analysis Service extension has been updated recently and maintaining partitions is one of the new features available.
Please feel free to use the latest version with the new option `partitionDeployment`

**Comment by aocall1** [comment]
> The Analysis Service extension has been updated recently and maintaining partitions is one of the new features available. Please feel free to use the latest version with the new option `partitionDeployment`

Thank you! This is really helpful and is exactly what we needed, I appreciate your response!

Aoife
