### ISSUE TITLE
Enhancement - Integrate Power BI Drillthrough

### ISSUE THREAD

**Issue by xsg13** [liprec/azurebi-docs#162]
Hi!

In Nov 2018 with the release of Power BI API 2.2.0 it is possible for custom visuals to connect with/use the drill through feature,

There is an example here on StackOverflow with how to implement this for D3 based custom visual (I'm guessing this one is).  
[https://stackoverflow.com/questions/46577192/power-bi-drillthrough-in-custom-visual](https://stackoverflow.com/questions/46577192/power-bi-drillthrough-in-custom-visual)

Could we get this added?  It would be awesome to use the D3 visual to drill though to other report pages.

Thanks!

**Comment by liprec** [comment]
Thanks for the suggestion, but currently I am still looking on how to integrated it with the `PBI` object
