### ISSUE TITLE
How to Delete multiple Linked Services, Datasets, Pipelines

### ISSUE THREAD

**Issue by apeyy** [liprec/azurebi-docs#163]
*Start issue here*
Deleting a single Linked Service, Dataset, Pipeline works. Is there a way to delete multiple Linked Services, Datasets, Pipelines?

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=5faa75e7-bfc2-4ba0-a07f-6f06563724ca
* document_url=https://azurebi-docs.jppp.org/vsts-extensions/azure-data-factory-delete.html

**Comment by liprec** [comment]
The `filter` option of the task is a RegEx filter, so with the correct expression it will delete multiple objects.
