### ISSUE TITLE
Assigning of Colors to states works, but gets mixed up, when e.g. by filtering new states are visible

### ISSUE THREAD

**Issue by martinsteine** [liprec/azurebi-docs#164]
When you assign state colors, and then depending on filters new states are visible, the the colors mix up. looks like it's depending on the number of different states..
This makes assigning colors to different states possible but useless, since the colors change, when there are different states then in another filter...

It needs to be possible to assign color to a value, which is then fixed...

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=58ef11d4-ac85-498a-be9d-d59663dcad33
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/event-viewer-changelog.html

**Comment by liprec** [comment]
Thanks for your feedback and this feature is part of the backlog, but currently the main focus is to get it certified...

**Comment by martinsteine** [comment]
Hi, i understand the urgency of getting it certified. It's a very useful visual here, with big potential. However, changing the colors every time destroys it's value totally. Hope you find some time to get this fixed soon. :)

**Comment by martinsteine** [comment]
Hi again. Do you know, when it it changing color? Is there a known workaround? What would we need to do, that it does not change color-assignment?
