### ISSUE TITLE
deploy-aas-db@1 task unable to configure advanced datasources

### ISSUE THREAD

**Issue by jkockx** [liprec/azurebi-docs#188]
Hi 

I'm wondering if the task already supports deploying the SSAS model with **connectionType 'advanced'** enabled.

I want to do this, because, for example, I want to be able to change the name of the datasource accross environments (see screenshot).

![image](https://user-images.githubusercontent.com/52573844/202455186-47b1d7a5-8b37-4e86-81e1-1ef72a1826f3.png)

The code I tried was the following (with variables defined in my Azure DevOps project): 

```
   - task: deploy-aas-db@1
      displayName: 'Deploy ${{ parameters.datamart }} model'
      inputs:
        connectedServiceNameARM: 'Data ARM'
        aasServer: 'asazure://northeurope.asazure.windows.net/mandmtabular01${{ parameters.env }}'
        databaseName: ${{ parameters.datamart }}
        loginType: inherit
        pathToModel: Tabular/${{ parameters.datamart }}/Tabular/Model.bim
        partitionDeployment: deploypartitions
        roleDeployment: retainroles
        connectionType: advanced
        datasources: | # connectionType = 'advanced'
          [
          {
              "name": "SQL/BI${{ parameters.env }};${{ parameters.datamart }}", 
              "authenticationKind": "UsernamePassword",
              "connectionDetails": {
                  "address": {
                      "server": "BI${{ parameters.env }}",
                      "database": "${{ parameters.datamart }}"
                  }
              },
              "credential": {
              "Username": "$(SqlUsername)",
              "Password": "$(SqlPassword)"
              }
          }
          ]
```

Unfortunatly, this task doesn't reconfigure anything on the SSAS server

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=4381b0c0-3a30-42ba-ad70-47e99b1994e1
* document_url=https://azurebi-docs.jppp.org/vsts-extensions/azure-analysis-service-deploy.html

**Comment by jkockx** [comment]
Had to use the TSML script task to configure the credentials correctly in the end. See https://azurebi-docs.jppp.org/vsts-extensions/azure-analysis-service-execute.html?tabs=docs-open

**Comment by tgauchet** [comment]
hello it works for me but you need to follow syntax of your .asdatabase file (the one proposed is obsolete or wrong)
go to section "dataSources":
and copy the json []
NB: on my side I have copied all for one datasource  except the type property ("type": "structured",)
