### ISSUE TITLE
Overlapping visual while applying filter.

### ISSUE THREAD

**Issue by VAMSI691468** [liprec/azurebi-docs#190]
Hi,
When using box & Whisker chart visual facing overlapping issue while filtering the data by slicer.
 After turning off data label for that visual and applied filter behaving normally.
After deselecting and applying filter it back the problem appears again. but I don't really know how to Fix this issue or give any more details that could help identify the cause of the problem... :-(
 

---
#### Document details
In the Visual 3 there is a overlapping issue Data is filtering for 1 month & visual appearing for 3 months
Data Lables are ON:
![image](https://user-images.githubusercontent.com/125556193/219348792-95a8615a-6c6e-4980-83b9-63a69d8b2ba5.png)

Same report when I Tested with data labels turned off and applied filter Visual is behaving normally.

![image](https://user-images.githubusercontent.com/125556193/219350092-bfab2631-d3d0-40f2-b03e-5ed7165aa9db.png)

 
 

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=4555c56c-3a13-42d3-a4d4-df34d7b4e455
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/box-and-whisker-chart.html

**Comment by liprec** [comment]
Thanks for the feedback and indeed the visual has its quirks regarding refreshing. Officially I am still working on releasing an updated version, but I am facing some challenges that halted the progress. But the good news is that I have solved a blocking issue and that I will start with updating the Box and Whisker chart again!

**Comment by VAMSI691468** [comment]
Thanks for your response!
One more issue I want to bring up to your notice facing some data color filtering Issue also in the same chart. 
for the 3 months have given different data colors but not filtering as same.
Hopefully this will also get fixed in the next release.

  
![image](https://user-images.githubusercontent.com/125556193/221151584-a1088319-7846-45ba-a138-27c1090e70f5.png)
