### ISSUE TITLE
d3js visuals are not showing up on Internet explorer. Currently using 11.225.14393.0. These visuals Works perfectly on chrome. 

### ISSUE THREAD

**Issue by darshan8800** [liprec/azurebi-docs#20]
*Start issue here*

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=2380fb48-08d2-44bc-aaa2-2decb8eeed18
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/index.html

**Comment by liprec** [comment]
The visual itself is working in Internet Explorer, so probably it is related to the custom D3JS code /JavaScript. Do remember that IE11 is only supporting ES5: so arrow function are not supported in Internet Explorer.  

Closing this issue for now.
