### ISSUE TITLE
If select all is bookmarked and data values are added, new select option appear unselected

### ISSUE THREAD

**Issue by johannes-celix** [liprec/azurebi-docs#22]
If select all is bookmarked and data values are added, new select option appear unselected.

This is a bit unfriendly as we import new data every night and we use this hierachy slicer as date selector.

We kindly ask to make an improvement for this.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by Nikkimirri** [comment]
I noticed this same behaviour, which is annoying, when users think they have selected all but new values are missing from selection. This case of Johannes was closed, what was the solution or was there?
