### ISSUE TITLE
Edit Button gone?

### ISSUE THREAD

**Issue by MartinBlo** [liprec/azurebi-docs#23]
Hello!

Why is it that sometimes the edit button is not in the context-menu  of the visualization?

Kind regards

Martin

![image](https://user-images.githubusercontent.com/34268144/49443028-8c5b1000-f7cb-11e8-8174-e951835f8592.png)

**Comment by liprec** [comment]
This is something with Power BI itself and not the visual: after editing and going back to the visual, the `Edit` option is indeed missing in the context menu.
You can refresh the data or alter the location of dimension of the visual to get it back.

**Comment by CrazyEnigma** [comment]
This is a great tool.  I cannot stress how cool it is to see d3 integrated with PBI.  Switching between pages will also do the trick.
