### ISSUE TITLE
Deprecated Visual

### ISSUE THREAD

**Issue by smjanalytics** [liprec/azurebi-docs#28]
*Start issue here*
Power Bi desktop is saying that this visual is using an old and unsupported version of the interface, and it will be deprecated soon. The slicer is no longer working in my dash.

Are we able to update the slicer so it works with the new versions? I'd hate to lose this functionality!

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
I have noticed that in some situations the Power BI will show this message for the HierarchySlicer.
But the visual will *not* be deprecated and soon being replaced by a new version. You can without problems ignore this message.
