### ISSUE TITLE
Issue with Hierarchy Slicer in Power B

### ISSUE THREAD

**Issue by MahaKoppu** [liprec/azurebi-docs#29]
Position of the checkboxes are going down in the hierarchy slicer when the report is published to Power BI service

I created a hierarchy slicer in Power BI desktop as shown below
![desktop](https://user-images.githubusercontent.com/46464958/50800739-58757d80-1296-11e9-83a5-7dc6d73d2e7a.PNG)
After publishing the report, it is displaying as below. 
![image](https://user-images.githubusercontent.com/46464958/50800784-94a8de00-1296-11e9-8039-55bfbac6370a.png)

The position of checkbox is going down, is there any other setting that need to changed or is this some bug?

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
This should not be a problem anymore. Can you validate if this issue is gone?
Thanks.

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
