### ISSUE TITLE
Collapsiblet ree 

### ISSUE THREAD

**Issue by SimonaMargarint** [liprec/azurebi-docs#30]
Hi team

can this visual be transformed into the below?
![image](https://user-images.githubusercontent.com/43440085/51602316-4c80f100-1f0f-11e9-84b4-99490ec5afe2.png)
Thanks
Simona

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=59bc6305-3908-4afa-bdfd-66ed39c91192
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/d3js.html

**Comment by liprec** [comment]
Sorry for the delay and you can take a look at the newest Decomposition Tree if that matches your requests: https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree
If not, you have to go and develop a custom visual either self or let someone develop it for you.

Thanks, Jan Pieter
