### ISSUE TITLE
Display problem with sharepoint + ie11

### ISSUE THREAD

**Issue by Florent-36** [liprec/azurebi-docs#34]
*Start issue here*
Slicer doesn't display with IE11 when the report is embedded in a sharepoint page ; no problem with Chrome or Firefox.
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
A new version of the HierrachySlicer will be released in a couple of weeks. Can you validate with the new version if this problem still exists? Thanks.

**Comment by Florent-36** [comment]
Hi,
Sure I can test,  let me know when it's ready and I'll tell you.
Thank you for the update !

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter

**Comment by Florent-36** [comment]
Hi,
I've still the same issue.
