### ISSUE TITLE
Empty Leaves

### ISSUE THREAD

**Issue by russty72** [liprec/azurebi-docs#36]
We have a handful of PBI Developers who love the Hierarchy Slicer. We notice a feature "Empty Leaves" with an on/off toggle. From your site it appears that this should allow jagged hierarchies and that turning this on should ignore lower hierarchy levels.

We have a corporate hierarchy with 5 levels total of Org Structure (Divisions, Departments, Grouped Cost Centers, Cost Centers, etc.) but not all strands have 5 levels.

Our hope is that this Empty Leaves feature will only show 2 or 3 levels where levels 4 and 5 are blank. Right now it is showing Levels 4 and 5 but with no text or description on those levels. Just a check box and then a blank text space.

Please advise on how the Empty Leaves feature works and if possible provide some sample data or a *.pbix file with this feature working.

Thanks!!

Russ

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
The current version only hides the items is they are 'real' empty or a `null` value. With the new version, wil be available in a couple of weeks, there are more options the hide the items.

**Comment by russty72** [comment]
Super info. Thank you Jan for the quick response!

**Comment by liprec** [comment]
Yes, the new version, v2, will become certified.

**Comment by russty72** [comment]
Jan,
Do we have a new version now with additional options to hide empty leaves? I'm still seeing empty leaves and the Hierarchy Slicer in my Power BI Desktop does not match the preview image shown in the Appsource site. Please see two attachments for more examples.
Thanks Jan!
Russ
![WhatAppSourceShowsInScreenshot_Hierarchy Slicer](https://user-images.githubusercontent.com/33669498/58577157-bd585280-81fa-11e9-9c41-43b3e1178345.JPG)
![What I'm Seeing_HierarchySlicer](https://user-images.githubusercontent.com/33669498/58577158-bdf0e900-81fa-11e9-80e5-967fe4694c75.JPG)

**Comment by liprec** [comment]
Hi @russty72,
AppSource is already reflecting v2 information, but this version is not yet available for everyone.
We are running in some late issues before it will become available.

**Comment by russty72** [comment]
Thanks so much Jan for the reply. I'm very excited about v2! I was able to use it briefly and it worked perfectly! Any chance I could get a copy? I would be happy to be s tester for you to provide any helpful feedback.

**Comment by russty72** [comment]
Thanks so much Jan for the reply. I'm very excited about v2! I was able to use it briefly and it worked perfectly! Any chance I could get a copy? I would be happy to be s tester for you to provide any helpful feedback.

**Comment by liprec** [comment]
Thanks for the offer. But at this moment the visual is already in the last steps before its release. Some patience is still needed unfortunately.

**Comment by russty72** [comment]
Thanks Jan for the heads up… Appreciate your update.
Russ

**Comment by Yash-GH** [comment]
> Thanks for the offer. But at this moment the visual is already in the last steps before its release. Some patience is still needed unfortunately.

Jan, just wanted to check if you have any estimated date for releasing v2.0? We had some deliverable's lined up and was wondering if v2.0 would be available, or have to come up with an alternative approach. 

Thanks.

**Comment by chizhova** [comment]
Hi there. Love the visual, but still got empty leaves in hierarchy branches with different depth
![image](https://user-images.githubusercontent.com/18233072/63749162-86eeaa00-c8b3-11e9-8ac6-f1b6a63d6cbe.png)

**Comment by liprec** [comment]
Hi @chizhova,

It looks to me that the values are text values containing 'null' and not empty values.
Can you add an extra conversion step to convert these values to empty values at your data retrieval?

-JP

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
