### ISSUE TITLE
Hierarchy Slicer Stopped Working

### ISSUE THREAD

**Issue by jeffmasse** [liprec/azurebi-docs#37]
Been using the hierarchy slicer for a couple years, with very few issues. Today, it suddenly stopped working for every Power BI project that uses it for date hierarchies (e.g., Year > Quarter > Month > Week). Seems to be working for other hierarchical data.

I am able to build new hierarchy slicers (using the same date fields) from scratch and those work. However, the existing date hierarchy slicers do NOT work.

EDIT: Working for SOME other hierarchical data. But most are broken.

EDIT: Started working again at approximately 4p EST.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by gayatriohri** [comment]
Same for me. Not working on any reports.  :(
