### ISSUE TITLE
D3.js Power BI visual: highlight and filtering

### ISSUE THREAD

**Issue by ba-tno** [liprec/azurebi-docs#39]
Hi,

In the [sample file](https://github.com/liprec/powerbi-d3jsvisual/releases/download/v1.1.0/D3jsVisual.Sample.pbix) the third page shows a collapsible tree.
Is there a way to make the nodes filter the data of the whole page when they're clicked? 
E.g. if I click the node `Mountain-100 Silver, 38` the page filters other visuals for that row(s) only?

**Comment by liprec** [comment]
At this moment there is no interaction available, but it is on the backlog for a future version.

**Comment by xsg13** [comment]
Is there any update on this item in the backlog?  This would be really awesome to have!

Thanks!

**Comment by rafaelxkr** [comment]
@liprec this feature is available?
