### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by jmlemercier** [liprec/azurebi-docs#4]
Hello JP, thanks for creating this tool !

I have a few questions though : I try to edit the JS code from this page https://bl.ocks.org/mbostock/4063423 in order to create a custom Sunburst data chart. I have imported the JSON sample file this page gives, and modified a few things in the JS code to try and adapt it, changing FROM : 

---------------------------------------
var width = 960,
    height = 700,
    radius = Math.min(width, height) / 2,
    color = d3.scale.category20c();

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height)
  .append("g")
    .attr("transform", "translate(" + width / 2 + "," + height * .52 + ")");

var partition = d3.layout.partition()
    .sort(null)
    .size([2 * Math.PI, radius * radius])
    .value(function(d) { return 1; });

var arc = d3.svg.arc()
    .startAngle(function(d) { return d.x; })
    .endAngle(function(d) { return d.x + d.dx; })
    .innerRadius(function(d) { return Math.sqrt(d.y); })
    .outerRadius(function(d) { return Math.sqrt(d.y + d.dy); });

d3.json("flare.json", function(error, root) {
  if (error) throw error;

  var path = svg.datum(root).selectAll("path")
      .data(partition.nodes)
    .enter().append("path")
      .attr("display", function(d) { return d.depth ? null : "none"; }) // hide inner ring
      .attr("d", arc)
      .style("stroke", "#fff")
      .style("fill", function(d) { return color((d.children ? d : d.parent).name); })
      .style("fill-rule", "evenodd")
      .each(stash);

  d3.selectAll("input").on("change", function change() {
    var value = this.value === "count"
        ? function() { return 1; }
        : function(d) { return d.size; };

    path
        .data(partition.value(value).nodes)
      .transition()
        .duration(1500)
        .attrTween("d", arcTween);
  });
});

// Stash the old values for transition.
function stash(d) {
  d.x0 = d.x;
  d.dx0 = d.dx;
}

// Interpolate the arcs in data space.
function arcTween(a) {
  var i = d3.interpolate({x: a.x0, dx: a.dx0}, a);
  return function(t) {
    var b = i(t);
    a.x0 = b.x;
    a.dx0 = b.dx;
    return arc(b);
  };
}

d3.select(self.frameElement).style("height", height + "px");
---------------------------------------

TO : 

----------------------------------------
var width = pbi.width,
    height = pbi.height,
    radius = Math.min(width, height) / 2,
    color = pbi.colors();

var svg = d3.select("#chart")
    .attr("width", width)
    .attr("height", height)
  	.append("g")
    .attr("transform", "translate(" + width / 2 + "," + height * .52 + ")");

var partition = d3.layout.partition()
    .sort(null)
    .size([2 * Math.PI, radius * radius])
    .value(function(d) { return 1; });

var arc = d3.svg.arc()
    .startAngle(function(d) { return d.x; })
    .endAngle(function(d) { return d.x + d.dx; })
    .innerRadius(function(d) { return Math.sqrt(d.y); })
    .outerRadius(function(d) { return Math.sqrt(d.y + d.dy); });

pbi.dsv(function(root) {

  var path = svg.datum(root).selectAll("path")
      .data(partition.nodes)
    .enter().append("path")
      .attr("display", function(d) { return d.depth ? null : "none"; }) // hide inner ring
      .attr("d", arc)
      .style("stroke", "#fff")
      .style("fill", function(d) { return color((d.children ? d : d.parent).name); })
      .style("fill-rule", "evenodd")
      .each(stash);

  d3.selectAll("input").on("change", function change() {
    var value = this.value === "count"
        ? function() { return 1; }
        : function(d) { return d.size; };

    path
        .data(partition.value(value).nodes)
      .transition()
        .duration(1500)
        .attrTween("d", arcTween);
  });
});

// Stash the old values for transition.
function stash(d) {
  d.x0 = d.x;
  d.dx0 = d.dx;
}

// Interpolate the arcs in data space.
function arcTween(a) {
  var i = d3.interpolate({x: a.x0, dx: a.dx0}, a);
  return function(t) {
    var b = i(t);
    a.x0 = b.x;
    a.dx0 = b.dx;
    return arc(b);
  };
}

d3.select(self.frameElement).style("height", height + "px");

-----------------------------------

Multiple problems then happen : 

1- The D3 chart remains blank, although I tried many changes in the JS code 
2- When I go back to report to visualize the chart and I go back to editing, the JS and CSS code disappears, only pbi remaining : and when I hit 'Save' when in pbi editing, the CSS code comes back but the JS code is replaced by the pbi code !!! 

I don't know if it's a JS mistake of mine or something other users experienced, but if you'd give me a hand, I would really appreciate it ! 

Jm

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=59bc6305-3908-4afa-bdfd-66ed39c91192

**Comment by jmlemercier** [comment]
Actually it looks like the JS code really needs the JSON "tree" structure as it calls for the d.children at one point, whereas here when I import the JSON into PowerBI it only creates a table, which destroys the parent-children relationship basically ?..

**Comment by liprec** [comment]
Indeed Power BI doesn't know the concept of hierarchy/tree data structures: it is always provided as a table. But you can take a look at the sample: https://github.com/liprec/powerbi-d3jsvisual/releases/download/v1.1.0/D3jsVisual.Sample.pbix.
The original code also uses a JSON tree dataset and I added an extra method to convert the Power BI table back to a tree JSON to be consumed by the visual.

**Comment by jmlemercier** [comment]
Ok I see, it's a bit tricky then because the translational function depends on the data fields, I should try to program one that could adapt to the data : still, I managed to produce your collapsible tree with my data after some modifications so that one's good. 

The data is a tree with name --> cname --> ccname --> size

However, I tried to apply it to the sunburst partition [(](https://bl.ocks.org/mbostock/4063423) and came up with that : 
_________________________________________________
`
function toJSON(data) {
    var flare = { name: "Node", children: [] },
        levels = ["name","cname"];

    // For each data row, loop through the expected levels traversing the output tree
    data.forEach(function(d){
        // Keep this as a reference to the current level
        var depthCursor = flare.children;
        // Go down one level at a time
        levels.forEach(function( property, depth ){

            // Look to see if a branch has already been created
            var index;
            depthCursor.forEach(function(child,i){
                if ( d[property] == child.name ) index = i;
            });
            // Add a branch if it isn't there
            if ( isNaN(index) ) {
                depthCursor.push({ name : d[property], children : []});
                index = depthCursor.length - 1;
            }
            // Now reference the new child array as we go deeper into the tree
            depthCursor = depthCursor[index].children;
            // This is a leaf, so add the last element to the specified branch
            if ( depth === levels.length - 1 ) depthCursor.push({ name : d.ccname, size : d.size });
        });
    });
    // End of conversion
    return flare;
}
`
_______________________________________________________

I also implemented the extra method in the data importing function as follows : 

_______________________________________________________
` 
pbi.dsv(function(error, data) {
  if (error) throw error;
  **var flare = toJSON(data);
  root = flare;**	 
  var path = svg.datum(root).selectAll("path")
      .data(partition.nodes)
    .enter().append("path")
      .attr("display", function(d) { return d.depth ? null : "none"; }) // hide inner ring
      .attr("d", arc)
      .style("stroke", "#fff")
      .style("fill", function(d) { return color((d.children ? d : d.parent).name); })
      .style("fill-rule", "evenodd")
      .each(stash);

  d3.selectAll("input").on("change", function change() {
    var value = this.value === "count"
        ? function() { return 1; }
        : function(d) { return d.size; };

    path
        .data(partition.value(value).nodes)
      .transition()
        .duration(1500)
        .attrTween("d", arcTween);
  });
}); `
_________________________________________________________________

But nothing shows up, and I can't manage to find what doesn't work : 
- is the import function not adapted to the kinf of data we translated ? (I ran the original JS code and it works in a browser)
- Are the other methods to adapt ?

Thank you for your help

Jm

**Comment by liprec** [comment]
I tried something my self: first I imported the given `flare.json` file and converted to a table with 5 columns: | level1 | level2 | level3 | level4 | size |.

And if I convert it with the function `toJSON` it will not give me the original `flare.json` structure.
I noticed two things:
- The converted tree had fixed levels, so levels with 'null' as key appeared.
- Missing attributes on the levels.

So I do not have a complete answer, but if you want to `copy-paste` the sunburst code from there need to be a correct conversion function. I am still looking for a generic method that I can include in the `pbi` object that everyone can use.

**Comment by liprec** [comment]
Added generic method at issue: liprec/powerbi-d3jsvisual#6

**Comment by CrazyEnigma** [comment]
In order to get a certain level of response to run-time error messaging, I've built a SVG graphic into the D3 code.

After:
`var svg = d3.select("#chart").attr("width", width+margin.left+margin.right).attr("height", height+margin.top+margin.bottom).append("g").attr("transform", "translate("+margin.left+","+margin.top+")");`

Add a graphic before calling the pbi.dsv method:
`var errorBox = svg.append("text")
    .attr("class","error")
    .style("visibility","hidden")
    .attr("fill", "red")
    .attr("x",0)
    .attr("y",0)
    .attr("width", width)
    .attr("height",height);`

Within the:
`pbi.dsv(function(data) {
    try {
        // coding
    } catch (err) {
        errorBox.text(err).style("visibility","visible");
    }
});`

The very least, it would determine the run-time errors.  The majority of the issues that I was having was a difference between d3 v3 and d3 v4, and learning the d3/svg paradigm in js.

The same can be done with a outputBox, and using:
`outputBox.text(JSON.stringify(data)).style("visibility","visible");`

**Comment by robinlosey** [comment]
This error handling code is a life saver!  Im Power BI, I'm now able to see the error "TypeError: d3.stratify is not a function".  This seems to indicate one of two things: 1) either d3-hierarchy is not included, but that seems unlikely as the sample uses "Tree" which also comes from d3-hierarchy, or 2) that this falls into the category of differences between d3 v3 and d3 v4. 

Is there a way to check within the Power BI D3 custom visual as to which version of d3 is being used?  How would I be able to get it to use v4 instead?
