### ISSUE TITLE
Search option doesnt work with Select ALL option Turned ON in Hierarchy Slicer

### ISSUE THREAD

**Issue by rajimishra** [liprec/azurebi-docs#40]
![image](https://user-images.githubusercontent.com/52261399/60218085-3e2b5e00-983c-11e9-9e90-0a81a04b646f.png)
![image](https://user-images.githubusercontent.com/52261399/60218265-d6294780-983c-11e9-8058-9c310fc2007d.png)

The Search option doesn't work if you have "Select All" turned on in the Selection option which is a bug and is impacting the use of the slicer as Users need both Select ALL & Search option enabled.
Request if you could look into the issue and let us know if there is a fix soon.
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Closing as this is a known issue (see [#44](https://github.com/liprec/powerbi-hierarchySlicer/issues/44)) and will be solved in the next v2 version which will be available anytime soon.
