### ISSUE TITLE
Box and Whiskers Plot Power BI: Visual not refreshing with slicer

### ISSUE THREAD

**Issue by JohannesTgit** [liprec/azurebi-docs#42]
If I switch with a slicer through our different material groups the visual is not refreshing itself in about 50% of the cases. This seems to be a new problem. I tried at different computers always generating the same issue. The visual has been performing nicely without any errors in the past (until ~2 weeks ago)

**Comment by liprec** [comment]
Hi @JohannesTgit 

Thanks for your feedback and sorry about the delay. Is this still an issue? ANd if yes, can you share a PBIX file with me? You can use my email: mail@datascenarios.nl

Thanks, Jan Pieter
