### ISSUE TITLE
Slicer does not support export for PowerPoint or PDF

### ISSUE THREAD

**Issue by upyrbutt** [liprec/azurebi-docs#43]
The slicer gives an ugly graph in place of a valid slicer in export to PowerPoint and to PDF files

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by AntonioMoller** [comment]
I have the same issue :-( it is a quite good visual but i need it to be verified by Microsoft so it can be supported in exports. 
in the limitation section on the support site it says that it cant be verified ??? why not ??
https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html?tabs=docs%2Cdocs-open

**Comment by liprec** [comment]
Version v2 will be certified, but is not yet available at this moment, but will be in the near future. There is still one scenario that is causing issues and therefor the v2 is not yet general available.

**Comment by RicoBiwan** [comment]
Hi
This slicer is fantastic and is great for our reports.
But i'd like to export the reports to PDF, and, even if it is now certified (V2), it doesn"t worK.
Do you know when the slicer will be ok for export, please ?
Thanks for your answer.
Eric.

**Comment by liprec** [comment]
Closing as it is related to liprec/powerbi-hierarchyslicer#34
