### ISSUE TITLE
Hierarchy Slicer control does not show levels empty leaves even when the 'Empty Leaves' option is turned On

### ISSUE THREAD

**Issue by Yash-GH** [liprec/azurebi-docs#44]
*
**Use Case:** 
Using this control to display Organization Staff hierarchy

**ISSUE 1:**
Hierarchy Slicer control **does not show levels empty leaves** even when the 'Empty Leaves' option is turned On.

**Issue 1 example:**
Level 1 - Root Node
Level 2 - Has 3 nodes (All Managers, so will have Level 3 populated)
Level 3 - Has 2 Managers and 1 Employees, so only two manager will have level 4 populated

After adding Fields 1, 2, 3 for the first 3 levels the hierarchy looks fine, as represented below:
- Level 1 Manager
    + Level 2 Manager 1
    + Level 2 Manager 2
     - Level 2 Manager 3
          . Level 3 Manager 1
          . Level 3 Manager 2
          . Level 3 Employee 1

After Adding Level 4 to the control, 'Level 3 Employee 1' gets eliminated from the control as there are no children.
- Level 1 Manager
    + Level 2 Manager 1
    + Level 2 Manager 2
     - Level 2 Manager 3
         + Level 3 Manager 1
         + Level 3 Manager 2
         **<This level gets dropped>**

**Expected Result:**
- Level 1 Manager
    + Level 2 Manager 1
    + Level 2 Manager 2
     - Level 2 Manager 3
         + Level 3 Manager 1
               . Level 4 Employee 2
               . Level 4 Employee 3
         -  Level 3 Manager 2
               . Level 4 Employee 4
               . Level 4 Employee 5
         -  Level 3 Employee 1

Based on the help/documentation looks like the 'Empty Leaves' option could be used to control if the empty leaves should be turned on or off. Turning the option On or Off has no affect on the control display.

**ISSUE 2:**
Selecting the node does not include the node itself, only includes the children in the selection.

**Issue 2 example:**
Level 1 - Root Node
Level 2 - Has 3 nodes (All Managers, so will have Level 3 populated)
Level 3 - Has 2 Managers and 1 Employees, so only two manager will have level 4 populated  

If Level 2 Manager is selected, the result only shows the children of level 2. The check box for Level 2 Manager and the levels below that is marked as selected, but only the levels below are included in the result, not the Level 2 Manager.  

Maybe this should be provided as a option switch, depending on the use case, the results may or may not want the selected node to be included. For example: If counting direct reports of the selected level, the selected row should not be included in the results/total count. But if doing a head count may want to include the node and the children in the results/total count.

Please let me know if there is a workaround for the issues mentioned above 
OR
There are any plans to enhance the control to address the issue.

Thank you.
*

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Can you share a PBIX with the described behavior?

**Comment by Yash1971** [comment]
Good Morning Jan,

Thank you for the quick acknowledgment and response, really appreciate it.

Sorry, I won’t be able to send the work PBIX file. However, I will mock the data up to replicate the scenario and create a PBIX file and send it to you shortly.

Was I clear in explaining the issue I encounter? Just based on the use case mentioned, do you know if the current version of the hierarchy selector control would work to -
1. Display mixed nodes? (Some may have children’s and some may not have children’s under the same parent node)
2. Return children as well as the selected parent node. (If I have another table control with details, it should filter and just show details of selected parent and children’s)

Also, may I know your role at Azure-BI? Just wanted to understand what level of support/assistance you can offer. I had some more feature suggestions to offer to make the control more powerful, wanted to know if I can share them with you.

Thank you.


- Yash
C: 848.391.6743
E: k_s@msn.com
(Sent from iPhone)
________________________________

**Comment by Yash1971** [comment]
> Can you share a PBIX with the described behavior?

Attached is the zipped file **PowerBI_Visual_POC_Test.zip** (Includes .PBIX and .XLSX file) with sample data and UI, highlighting the issue and the desired results. 

Your input/feedback would be greatly appreciated.

[PowerBI_Visual_POC_Test.zip]
(https://github.com/liprec/azurebi-docs/files/3495143/PowerBI_Visual_POC_Test.zip)

**Comment by Yash-GH** [comment]
Hi Jan, did you get a chance to check out the .PBIX file highlighting the issue? 
Is the option 'Empty Leaves' meant for this Use Case?

**Comment by liprec** [comment]
Hi @Yash-GH,

Sorry, but I didn't have the time yet to look at your problem. I will in the next couple of days!

-JP

**Comment by liprec** [comment]
Hi @Yash-GH,

The reason that you don't get the desired hierarchy is related to your datamodel.
At this moment all the staff levels are in separate tables as a 'snowflake': there are linked to each other via relations. Big disadvantages of a snowflake model is that the relations between the levels are 'inner joins', so only records from both sides are shown. Even if you use a table visual you see the same result: for level 1 - 4 I get 3 records missing all the records without a level 4.

Best option is to merge all the levels to one table and use an left join so that the non existing nodes can be set to 'null' and then those items will be removed by the HierarchySlicer to get your desired/expected result. 

Hope that this helps.

-JP

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
