### ISSUE TITLE
Hierarchy Slicer control is not certified 

### ISSUE THREAD

**Issue by ppserzo** [liprec/azurebi-docs#45]
Hierarchy Slicer control says it is certified 2.0.19 but it is not.  We can only use certified custom controls.  Do you have a date when this will be certified?

**Comment by liprec** [comment]
Version v2 will be certified, but is not yet at this moment. Main reason: there is still a scenario that is causing issues and therefor the v2 is not yet general available.

**Comment by ppserzo** [comment]
Thank you Jan.  Any idea on date it will be certified?   (I appreciate it)

**Comment by liprec** [comment]
Closing as a duplicate of /liprec/powerbi-hierarchySlicer#34
