### ISSUE TITLE
Hierarchy Slicer - Default filter selections saved for the reports get unchecked without Manual Interventation ,possibly after Scheduled Refresh

### ISSUE THREAD

**Issue by rajimishra** [liprec/azurebi-docs#48]
![image](https://user-images.githubusercontent.com/52261399/64201740-5da6be80-ce5d-11e9-8e7e-f2b7e8306993.png)

The default selection set for the filters gets unchecked without any manual intervention.
It looks possibly happening after the Scheduled Data Refresh.
We have been observing this for quite sometime now & it keeps on happening.
Could you please have a look into it in order to let us know incase we are missing some settings or its a bug.

**Comment by rajimishra** [comment]
Hi Team,

Any updates ?

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter

**Comment by rajimishra** [comment]
Hi Jan,

We found a new problem wherein the Business users aren't able to select more than 2 values for any selector . Once you select more than 2 values , the slicer blanks all the values.

Could you please help on the same or suggest any alternatives.

I am copied my Offshore team as well.

Regards
[cid:image009.png@01D5E0C5.92A23220]
Rajib Mishra
Capgemini | Coca-Cola BI Front-End Team
Atlanta office Complex
Atlanta, GA 30313

Mob.: 404.317.8947 / 469.970.3450
Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>
Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>
[Capgemini_Logo_2COL_CMYK]

Connect with Capgemini:
[cid:image003.gif@01D5E0C5.9266D6D0]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.gif@01D5E0C5.9266D6D0]<http://www.twitter.com/capgemini>[cid:image005.gif@01D5E0C5.9266D6D0]<http://www.facebook.com/capgemini>[cid:image006.gif@01D5E0C5.9266D6D0]<http://www.linkedin.com/company/capgemini>[cid:image007.gif@01D5E0C5.9266D6D0]<http://www.slideshare.net/capgemini>[cid:image008.gif@01D5E0C5.9266D6D0]<http://www.youtube.com/capgeminimedia>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.
