### ISSUE TITLE
search text font size does not change for hierarchy slicer (power bi)

### ISSUE THREAD

**Issue by lvbwwang** [liprec/azurebi-docs#49]
I use hierarchy slicer for my power bi report. It seems like the search text font size does not change even though i enlarge the font size to 40. 
Also, it is possible to add an eraser icon to clear the selection.

Thanks,
Wenchi

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
In a couple of weeks a new version will be released and in this version there are improvements in the text sizing.

-JP

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
