### ISSUE TITLE
Hierarchy Slicer: Shows Blank

### ISSUE THREAD

**Issue by bravespiano5** [liprec/azurebi-docs#50]
The visual keeps showing blank on the Power Bi Desktop (Sept-19 version). It appears fine when added but after closing out and reopening, it either shows blank initially or after navigating to a separate tab/page, blank.

**Comment by liprec** [comment]
Can you share a sample with the behavior for me to see what is happening?

Thanks, JP

**Comment by bravespiano5** [comment]
![image](https://user-images.githubusercontent.com/55611054/65718561-cacefd80-e071-11e9-9d0d-c99ffcafb1de.png)

**Comment by bravespiano5** [comment]
![image](https://user-images.githubusercontent.com/55611054/65718602-dfab9100-e071-11e9-952b-08a1f73e10a9.png)

**Comment by liprec** [comment]
Is it also possible to share a (sample) pbix file with the same behavior?

Thanks, JP

**Comment by bravespiano5** [comment]
I'm not sure if sending you a temp file will work, or rather allow you to troubleshoot, as we use direct query?

**Comment by bravespiano5** [comment]
Hi JP,

See the attached temp file. I'm still having issues with this visual and it's used throughout our Power BI reports so it's causing an issue when an update is required.

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
