### ISSUE TITLE
Selecting a parent node only in a Hierarchy Slicer

### ISSUE THREAD

**Issue by markmohsen** [liprec/azurebi-docs#51]
Hello .. Thanks for the amazing HierarchySlicer ..
I'm using it for an organizational Hierarchy, 
Sometimes I need to choose a manager only without his underlying employees.
Is this possible in the HierarchySlicer ? 

Thanks in advance :) 

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
No, this is not possible yet, but in a next version there will be some more options of selection related to items.

-JP
