### ISSUE TITLE
Doesn't appear to be compatible with powerBI bookmarks

### ISSUE THREAD

**Issue by soldstatic** [liprec/azurebi-docs#52]
See here for additional details: https://community.powerbi.com/t5/Desktop/Using-bookmarks-clear-Hierarchy-Slicer-filters/m-p/440097/highlight/false#M203178

![BookmarkFilterNotCleared2](https://user-images.githubusercontent.com/55848151/65705428-0bb51b00-e04e-11e9-9009-bffcfabc9134.gif)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Currently bookmarks are supported by the HierarchySlicer.
Can you update the bookmarks with the correct selections and try again?

Thanks, JP

**Comment by soldstatic** [comment]
Hey JP, I guess I don't know how to do that, but I have updated the
bookmark after creation and also tested with a new bookmark. I have the
bookmark set to 'all visuals' . It still behaves as seen in the image above.
