### ISSUE TITLE
Adding measures to "Values" does nothing

### ISSUE THREAD

**Issue by lobster4242** [liprec/azurebi-docs#53]
Hello @liprec !
I'm using Hierarchy Slicer to display Values, like in this video:
https://youtu.be/DW5NZHTZlPw?t=389 (6:29)

Since 02.10.2019 adding a measure to "Values" part does not affect the visual.

Please have a look at my small example attached.
[HierarchySlicer_MeasureTest.zip](https://github.com/liprec/azurebi-docs/files/3681286/HierarchySlicer_MeasureTest.zip)

**Comment by liprec** [comment]
Hi,

The 'Values' field was not intended to be part of the hierarchy, but in some releases it accidentally was part of the hierarchy as shown in the video. With the value filter you can filter the items with no values, like show only sales managers with this year sales.

-JP

**Comment by lobster4242** [comment]
This 'Values' field feature in the visual was really usefull and was giving value to my reports.

If the 'Values' field would not be a part of HierarchySlicer could I use an old version of HierarchySlicer as an (another) custom visual in my report?

**Comment by liprec** [comment]
But can't you add the measure directly to the hierarchy as a field?

**Comment by lobster4242** [comment]
... I have tried one more time and, unfortunatelly, I can't.
Basically with HierarchySlicer I was able to slice by measure. I suppose it was not intended, but if somehow I could use an earlier version of HierarchySlicer (for example 2.0.16) I will show you an example.

**Comment by lobster4242** [comment]
Hello @liprec

Feature to add measures to Slicer's "Value" filed is important part of our PowerBi reports.

Here is my example how I use measures in HierarchySlicer

Imagine we have 3 Stores and any day could get a score for any store:
![image](https://user-images.githubusercontent.com/56077631/66133067-bacd9580-e5fe-11e9-9401-231c4b68aa89.png)

The task is to have a slicer to show only stores with 0 scores:
Like this
![image](https://user-images.githubusercontent.com/56077631/66133380-3d565500-e5ff-11e9-9649-d87d5a9f3847.png)

And to have it work dynamicly with other slicers
If we selected only 01.01.2019 and 03.01.2019 we would get this result:
![image](https://user-images.githubusercontent.com/56077631/66133709-d08f8a80-e5ff-11e9-9f41-47dae320c192.png)

Basically, the task is to slice by measure, since we wanted all scores of stores that have at least one Zero score in selected period.

DAX documentation said that it isn't possible to slice by measure, but I have used your slicer to make this work!

Please find attached file that has a "Measure1"
[HierarchySlicer_MeasureTest2.zip](https://github.com/liprec/azurebi-docs/files/3686490/HierarchySlicer_MeasureTest2.zip)

To set up slicer (old version of it) first add a "Measure1" to Values and "lvl1" to Fields
![image](https://user-images.githubusercontent.com/56077631/66134449-06813e80-e601-11e9-9a1c-8b7383085f1f.png)

With the example above I want to pinpoint the value of this feature and kindly ask you specify if the feature of "Value" field will be retuned or completely removed?

**Comment by lobster4242** [comment]
Today I find out that Slicer works fine, like before! Thank you so much!

Here is complete working example of using measure in HierarchySlicer:
[HierarchySlicer_MeasureTest2.zip](https://github.com/liprec/azurebi-docs/files/3689250/HierarchySlicer_MeasureTest2.zip)

**Comment by lobster4242** [comment]
Hello @liprec

Today adding a measure to "Values" part does not affect the visual again.

This feature is commonly used in client's reports and bring a lot of business value.

**Comment by liprec** [comment]
Hi @lobster4242,

On Monday a new version of the HierarchySlicer has been released, but I can add the `Measure1` to the `Values` field. And to me it looks like it is working as expected: only items with a `Measure1` value is shown in the slicer.
Probably I am missing something related to your issue.

-JP

**Comment by lobster4242** [comment]
Hello @liprec
Thanks for quick reply

I've described the example in my comment from Oct 3

Now It's just impossible to achive the result

If its needed I could explain what was the result in a skype call

**Comment by liprec** [comment]
HI @lobster4242,

Feel free to schedule a skype call. You can use my email mail@datascenarios.nl.
And regarding scheduling: I am in the CET timezone.

-JP

**Comment by liprec** [comment]
Closing the issue and if it is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
