### ISSUE TITLE
Hierarchy Slicer not working Internet Explorer. It is working in Chrome

### ISSUE THREAD

**Issue by jainn4** [liprec/azurebi-docs#54]
The hierarchy slicer is not rendering in Internet Explorer. It is working fine in Chrome

Thanks
Nishant

**Comment by liprec** [comment]
At this moment there is an issue with the slicer in Internet Explorer and a fix is on its way.

Thanks, Jan Pieter

**Comment by jainn4** [comment]
Thanks mate. Appreciate the response.

**Comment by oscar216** [comment]
Hi, any update/ETA on this? Thanks!

**Comment by oscar216** [comment]
Looks like it's working again?

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
