### ISSUE TITLE
HierarchySlicer

### ISSUE THREAD

**Issue by Zuhal76** [liprec/azurebi-docs#55]
*Start issue here*

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=2380fb48-08d2-44bc-aaa2-2decb8eeed18
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/index.html

**Comment by liprec** [comment]
Hi @Zuhal76,

Can you share what you issue is?

Thanks, Jan Pieter
