### ISSUE TITLE
New Version Released?

### ISSUE THREAD

**Issue by russty72** [liprec/azurebi-docs#56]
Hi Jan. We are using and loving the Hierarchy slicer but noticed that our report in Production that is using the slicer now has 2 titles across the top. My guess is one is a Title and one is a Header. Did you recently update the Hierarchy Slicer visual that would make some of the features work differently in the PBI Service?

If so congrats! And please let me know what the new features/functionality are.
Kind Regards,
Russ
Slalom LLC, Data & Analytics, Seattle, WA

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
Hi Rusty,

The new version V2 is released today and probably that is causing the 2 titles at the top.
Can you share a screenshot or a sample PBIX file of the 2 titles, so I can take a look what is causing this?

Thanks, JP

**Comment by russty72** [comment]
![Hierarchy Slicer now showing both Header and Title](https://user-images.githubusercontent.com/33669498/66067437-6f34c200-e500-11e9-9157-ca71b031798d.png)
Hey Jan! Congrats on the new version! It looks great and I love the new functionality. Here's what we are seeing now... My guess is the default was changed to that both the Header and Title are on by default now...

**Comment by russty72** [comment]
The fix for us is to turn off the Title and only use the Header. Then we have to update the font coloring and size of the header and use the new Font Weight to make the font match other slicers that are the Microsoft default. For example to get Segoe (Bold) font size 10 to match the Microsoft default font of other slicers we have to pick Segoe (Bold), Font weight = Semi bold, and font size 10. Then it looks pretty close :-)

**Comment by russty72** [comment]
Let me know Jan if you need any additional info. The main issue seems to be that when the new version landed it did not keep the settings we had applied on the previous version. So we lost some formatting. Should we manually update our files that now appears to have an altered Hierarchy slicer? Or we can wait if you are planning to release another version that maintains existing formatting. Let me know so I can advise my client how to proceed. Thanks!

**Comment by adamlofton** [comment]
Hello Jan.

This is Adam, Russ’s team lead at work.  We are experiencing the same issue again with the slicer and the assumption is that an update has occurred with MSFT.  

How can we prioritize a solution for this issue ASAP, as our customers are experiencing an outage on 6 reports that are leveraging this slicer?  Appreciate any direction you can provide!

**Comment by russty72** [comment]
Hey Jan. Good morning from Seattle. I'm following up on my manager Adam Lofton's message above. We are seeing default settings in the Hierarchy Slicer change again. 

I'll upload a previous image to show what is happening. Basically the Title and Slicer Header are toggling on or off when Microsoft pushes updates or when you are pushing updates to the Hierarchy Slicer. Our current config is to turn off the Title (so when this turns on automatically it throws off the visual as it has 2 titles) and our other config is to format the Slicer Header with a bold text. 

Is there anyway we can know ahead of time when an update will happen and if it will impact existing settings to the Hierarchy Slicer so our users do not lose functionality?
![image](https://user-images.githubusercontent.com/33669498/67226343-8a9d3980-f3e9-11e9-8aeb-0839d9e03ba3.png)
