### ISSUE TITLE
Plenty of issues with new Version of Hierarchy Slicer

### ISSUE THREAD

**Issue by rajimishra** [liprec/azurebi-docs#57]
Today afternoon @3 PM EST , all of a sudden we have experienced the below issues
1.The Slicer selections went off Automatically
2.Date values/object values within slicers were not being seen
3. After every refresh , the default selections just went off
It had a major business impact.
Any inputs/leads would be appreciated?
We have also brought this to Microsoft's notice as one of the major customers have been impacted.
![image](https://user-images.githubusercontent.com/52261399/66090567-01b18180-e552-11e9-8188-26978f610ff9.png)
![image](https://user-images.githubusercontent.com/52261399/66090597-273e8b00-e552-11e9-8220-a95140181db6.png)

**Comment by liprec** [comment]
Sorry to hear that, but I need some more info to determine what can cause the issue:
What data source are you using?
And if you recreate the slicer, is the behavior still the same?

**Comment by rajimishra** [comment]
Hi Jan,
The data source is Teradata.
Yes after every scheduled refresh completion,this issue reoccurs.
As this application was productionalized,so business has raised concerns

Regards,
Rajib
________________________________

**Comment by liprec** [comment]
Are you using Power BI and Teradata with DirectQuery? Or using the import mode?

**Comment by rajimishra** [comment]
We are using Power BI & TD with import mode

Regards,
[cid:image004.png@01D4A745.C354BEC0]
Rajib Mishra
Capgemini | Coca-Cola BI Front-End Team
Atlanta office Complex
Atlanta, GA 30313

Mob.: 404.317.8947 / 469.970.3450
Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>
Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>

[Capgemini_Logo_2COL_CMYK]

Connect with Capgemini:
[cid:image003.png@01D34206.6D7CAA80]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.png@01D34206.6D7CAA80]<http://www.twitter.com/capgemini>[cid:image005.png@01D34206.6D7CAA80]<http://www.facebook.com/capgemini>[cid:image006.png@01D34206.6D7CAA80]<http://www.linkedin.com/company/capgemini>[cid:image007.png@01D34206.6D7CAA80]<http://www.slideshare.net/capgemini>[cid:image008.png@01D34206.6D7CAA80]<http://www.youtube.com/capgeminimedia>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.

**Comment by liprec** [comment]
Strange, those scenarios should be working.
Probably best to follow-up offline: is it possible to send me an email (mail@datascenarios.nl) and then determine what is the easiest way to debug this issue.

**Comment by rajimishra** [comment]
Hi Jan,

I had raised a similar issue - https://github.com/liprec/azurebi-docs/issues/48

It's very weird as the Slicer default selections goes off after the Scheduled Refresh. Not sure what is doing that as I have removed the interactions as well on Power BI

Regards,
[cid:image004.png@01D4A745.C354BEC0]
Rajib Mishra
Capgemini | Coca-Cola BI Front-End Team
Atlanta office Complex
Atlanta, GA 30313

Mob.: 404.317.8947 / 469.970.3450
Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>
Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>

[Capgemini_Logo_2COL_CMYK]

Connect with Capgemini:
[cid:image003.png@01D34206.6D7CAA80]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.png@01D34206.6D7CAA80]<http://www.twitter.com/capgemini>[cid:image005.png@01D34206.6D7CAA80]<http://www.facebook.com/capgemini>[cid:image006.png@01D34206.6D7CAA80]<http://www.linkedin.com/company/capgemini>[cid:image007.png@01D34206.6D7CAA80]<http://www.slideshare.net/capgemini>[cid:image008.png@01D34206.6D7CAA80]<http://www.youtube.com/capgeminimedia>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.

**Comment by rajimishra** [comment]
Hi Jan,

One more issue - the Expand filter option doesn't work intermittently in IE . Is it a Known issue ?

Regards,
[cid:image004.png@01D4A745.C354BEC0]
Rajib Mishra
Capgemini | Coca-Cola BI Front-End Team
Atlanta office Complex
Atlanta, GA 30313

Mob.: 404.317.8947 / 469.970.3450
Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>
Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>

[Capgemini_Logo_2COL_CMYK]

Connect with Capgemini:
[cid:image003.png@01D34206.6D7CAA80]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.png@01D34206.6D7CAA80]<http://www.twitter.com/capgemini>[cid:image005.png@01D34206.6D7CAA80]<http://www.facebook.com/capgemini>[cid:image006.png@01D34206.6D7CAA80]<http://www.linkedin.com/company/capgemini>[cid:image007.png@01D34206.6D7CAA80]<http://www.slideshare.net/capgemini>[cid:image008.png@01D34206.6D7CAA80]<http://www.youtube.com/capgeminimedia>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.








Classified - Confidential
From: Rajib Mishra [C]
Sent: Thursday, October 3, 2019 10:51 AM
To: liprec/azurebi-docs <reply@reply.github.com>; liprec/azurebi-docs <azurebi-docs@noreply.github.com>; mail@datascenarios.nl
Cc: Author <author@noreply.github.com>
Subject: RE: [liprec/azurebi-docs] Plenty of issues with new Version of Hierarchy Slicer (#57)

Hi Jan,

I had raised a similar issue - https://github.com/liprec/azurebi-docs/issues/48

It's very weird as the Slicer default selections goes off after the Scheduled Refresh. Not sure what is doing that as I have removed the interactions as well on Power BI

Regards,
[cid:image004.png@01D4A745.C354BEC0]
Rajib Mishra
Capgemini | Coca-Cola BI Front-End Team
Atlanta office Complex
Atlanta, GA 30313

Mob.: 404.317.8947 / 469.970.3450
Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>
Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>

[Capgemini_Logo_2COL_CMYK]

Connect with Capgemini:
[cid:image003.png@01D34206.6D7CAA80]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.png@01D34206.6D7CAA80]<http://www.twitter.com/capgemini>[cid:image005.png@01D34206.6D7CAA80]<http://www.facebook.com/capgemini>[cid:image006.png@01D34206.6D7CAA80]<http://www.linkedin.com/company/capgemini>[cid:image007.png@01D34206.6D7CAA80]<http://www.slideshare.net/capgemini>[cid:image008.png@01D34206.6D7CAA80]<http://www.youtube.com/capgeminimedia>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.

**Comment by rajimishra** [comment]
Hi Jan,

Just following up,once again the filters went off @ 1:30 PM EST which is again wierd as we didn't have any refresh scheduled. I am now really worried as it's throwing off the business users.

Regards,
Rajib
________________________________
From: Rajib Mishra [C]
Sent: Thursday, October 3, 2019 11:24:11 AM
To: liprec/azurebi-docs <reply@reply.github.com>; liprec/azurebi-docs <azurebi-docs@noreply.github.com>; mail@datascenarios.nl <mail@datascenarios.nl>
Cc: Author <author@noreply.github.com>
Subject: RE: [liprec/azurebi-docs] Plenty of issues with new Version of Hierarchy Slicer (#57)


Hi Jan,



One more issue – the Expand filter option doesn’t work intermittently in IE . Is it a Known issue ?



Regards,

[cid:image004.png@01D4A745.C354BEC0]

Rajib Mishra

Capgemini | Coca-Cola BI Front-End Team

Atlanta office Complex

Atlanta, GA 30313



Mob.: 404.317.8947 / 469.970.3450

Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>

Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>



[Capgemini_Logo_2COL_CMYK]



Connect with Capgemini:
[cid:image003.png@01D34206.6D7CAA80]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.png@01D34206.6D7CAA80]<http://www.twitter.com/capgemini>[cid:image005.png@01D34206.6D7CAA80]<http://www.facebook.com/capgemini>[cid:image006.png@01D34206.6D7CAA80]<http://www.linkedin.com/company/capgemini>[cid:image007.png@01D34206.6D7CAA80]<http://www.slideshare.net/capgemini>[cid:image008.png@01D34206.6D7CAA80]<http://www.youtube.com/capgeminimedia>



Please consider the environment and do not print this email unless absolutely necessary.

Capgemini encourages environmental awareness.















Classified - Confidential

From: Rajib Mishra [C]
Sent: Thursday, October 3, 2019 10:51 AM
To: liprec/azurebi-docs <reply@reply.github.com>; liprec/azurebi-docs <azurebi-docs@noreply.github.com>; mail@datascenarios.nl
Cc: Author <author@noreply.github.com>
Subject: RE: [liprec/azurebi-docs] Plenty of issues with new Version of Hierarchy Slicer (#57)



Hi Jan,



I had raised a similar issue - https://github.com/liprec/azurebi-docs/issues/48



It’s very weird as the Slicer default selections goes off after the Scheduled Refresh. Not sure what is doing that as I have removed the interactions as well on Power BI



Regards,

[cid:image004.png@01D4A745.C354BEC0]

Rajib Mishra

Capgemini | Coca-Cola BI Front-End Team

Atlanta office Complex

Atlanta, GA 30313



Mob.: 404.317.8947 / 469.970.3450

Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>

Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>



[Capgemini_Logo_2COL_CMYK]



Connect with Capgemini:
[cid:image003.png@01D34206.6D7CAA80]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.png@01D34206.6D7CAA80]<http://www.twitter.com/capgemini>[cid:image005.png@01D34206.6D7CAA80]<http://www.facebook.com/capgemini>[cid:image006.png@01D34206.6D7CAA80]<http://www.linkedin.com/company/capgemini>[cid:image007.png@01D34206.6D7CAA80]<http://www.slideshare.net/capgemini>[cid:image008.png@01D34206.6D7CAA80]<http://www.youtube.com/capgeminimedia>



Please consider the environment and do not print this email unless absolutely necessary.

Capgemini encourages environmental awareness.

**Comment by rajimishra** [comment]
List of Issues observed since yesterday
I had raised a similar issue - #48
**It's very weird as the Slicer default selections goes off after the Scheduled Refresh. Not sure what is doing that as I have removed the interactions as well on Power BI**
**One more issue - the Expand filter option doesn't work intermittently in IE . Is it a Known issue ?**

**Just following up,once again the filters went off @ 1:30 PM EST which is again wierd as we didn't have any refresh scheduled. I am now really worried as it's throwing off the business users.**

**Comment by liprec** [comment]
The latest version has been replaced by an older version as there were issues with Internet Explorer.
A new version is being released in a couple of weeks.

**Comment by rajimishra** [comment]
Thank you for the update.

One more defect was raised by business

  *   The filter values selected within the Hierarchy Slicer don't get applied to the underlying data export.

Regards
[cid:image004.png@01D4A745.C354BEC0]
Rajib Mishra
Capgemini | Coca-Cola BI Front-End Team
Atlanta office Complex
Atlanta, GA 30313

Mob.: 404.317.8947 / 469.970.3450
Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>
Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>

[Capgemini_Logo_2COL_CMYK]

Connect with Capgemini:
[cid:image003.png@01D34206.6D7CAA80]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.png@01D34206.6D7CAA80]<http://www.twitter.com/capgemini>[cid:image005.png@01D34206.6D7CAA80]<http://www.facebook.com/capgemini>[cid:image006.png@01D34206.6D7CAA80]<http://www.linkedin.com/company/capgemini>[cid:image007.png@01D34206.6D7CAA80]<http://www.slideshare.net/capgemini>[cid:image008.png@01D34206.6D7CAA80]<http://www.youtube.com/capgeminimedia>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.

**Comment by rajimishra** [comment]
Hello,

Was there a version released today as I observed my filters getting unchecked without any refresh @2PM EST onwards today

Regards,
[cid:image004.png@01D4A745.C354BEC0]
Rajib Mishra
Capgemini | Coca-Cola BI Front-End Team
Atlanta office Complex
Atlanta, GA 30313

Mob.: 404.317.8947 / 469.970.3450
Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>
Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>

[Capgemini_Logo_2COL_CMYK]

Connect with Capgemini:
[cid:image003.png@01D34206.6D7CAA80]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.png@01D34206.6D7CAA80]<http://www.twitter.com/capgemini>[cid:image005.png@01D34206.6D7CAA80]<http://www.facebook.com/capgemini>[cid:image006.png@01D34206.6D7CAA80]<http://www.linkedin.com/company/capgemini>[cid:image007.png@01D34206.6D7CAA80]<http://www.slideshare.net/capgemini>[cid:image008.png@01D34206.6D7CAA80]<http://www.youtube.com/capgeminimedia>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.








Classified - Confidential
From: Rajib Mishra [C]
Sent: Monday, October 21, 2019 10:41 AM
To: liprec/azurebi-docs <reply@reply.github.com>; liprec/azurebi-docs <azurebi-docs@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [liprec/azurebi-docs] Plenty of issues with new Version of Hierarchy Slicer (#57)

Thank you for the update.

One more defect was raised by business

  *   The filter values selected within the Hierarchy Slicer don't get applied to the underlying data export.

Regards
[cid:image004.png@01D4A745.C354BEC0]
Rajib Mishra
Capgemini | Coca-Cola BI Front-End Team
Atlanta office Complex
Atlanta, GA 30313

Mob.: 404.317.8947 / 469.970.3450
Email: rajimishra@coca-cola.com<mailto:rajimishra@coca-cola.com>
Email: rajib.mishra@capgemini.com<mailto:rajib.mishra@capgemini.com>

[Capgemini_Logo_2COL_CMYK]

Connect with Capgemini:
[cid:image003.png@01D34206.6D7CAA80]<http://www.capgemini.com/insights-and-resources/blogs>[cid:image004.png@01D34206.6D7CAA80]<http://www.twitter.com/capgemini>[cid:image005.png@01D34206.6D7CAA80]<http://www.facebook.com/capgemini>[cid:image006.png@01D34206.6D7CAA80]<http://www.linkedin.com/company/capgemini>[cid:image007.png@01D34206.6D7CAA80]<http://www.slideshare.net/capgemini>[cid:image008.png@01D34206.6D7CAA80]<http://www.youtube.com/capgeminimedia>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.

**Comment by liprec** [comment]
Accidentally a wrong version of the HierarchySlicer has been released by Microsoft which is causing this behavior, but now the correct working version is available again.

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
