### ISSUE TITLE
Hierarchy Slicer - issue selecting single items

### ISSUE THREAD

**Issue by Missberty** [liprec/azurebi-docs#58]
I have use the Hierarchy slicer for date selections on my Power BI reports, 

I have it set with the fields month, year and start of week

![image](https://user-images.githubusercontent.com/56111024/66111669-3b6da100-e5c1-11e9-90bf-568b92c58003.png)

Since the new update I cannot select a single item.  When I select the year 2020 the slicer will also select 2019 making it unusable.

I love using this slicer as it makes my reports so easy for the users. I really hope this is something that can be fixed quickly!

Thanks

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
Sorry to hear that, but I need some more info to determine what can cause the issue:
What data source are you using? And if you recreate the slicer, is the behavior still the same?

-JP

**Comment by Missberty** [comment]
Hi,

Thank you for such a quick response!

I removed the slicer from report tab, and then re-added it, and it still have the same issue. I’ve not tried to delete the custom visual and re-adding it.The data source is SQL database. I have multiple reports using this slicer with the same issue.

Below is a screen shot of how the slicer looks

[cid:image001.png@01D579D0.FC894270]

Many thanks

Sarah

**Comment by Missberty** [comment]
Hi,

We are seeing a re-occurrence of this issue again.  It does not seem to effect every filter, but where it does the filter is very blurry too:

![image](https://user-images.githubusercontent.com/56111024/68593154-b2356e00-048c-11ea-80f0-6e898ad98fd3.png)

**Comment by liprec** [comment]
There is an issue when multi-select is enabled and the option 'Hide members' is set. A fix will be available in the next couple of weeks.

Thanks, Jan Pieter

**Comment by liprec** [comment]
Solved with the latest v2.1.3 release
