### ISSUE TITLE
Hierarchy Slicer not working in power bi report server after September 2019 release update

### ISSUE THREAD

**Issue by RavinderSunkara** [liprec/azurebi-docs#59]
*Start issue here*
Hierarchy Slicer Visuals are working fine in the system but when we deploy it to Power BI report server it is not working.  Request you to provide a work around for this issue.

Regards,
Ravinder Sunkara
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @RavinderSunkara ,

What browser are you using with Power Bi Report Server? 

Thanks, JP

**Comment by RavinderSunkara** [comment]
Hi @liprec 
I have tired both in Internet explorer and Chrome too.

**Comment by RavinderSunkara** [comment]
Hi @liprec
Even tired it in firefox still it is not working.

**Comment by liprec** [comment]
Hi @RavinderSunkara ,

I am looking into this issue and what is causing this.
Thanks for the info.

-JP

**Comment by liprec** [comment]
At this moment it should not be a problem anymore as an older version is now available.

**Comment by RavinderSunkara** [comment]
Thank you @liprec for the update. Hierarchy Slicer is working fine since yesterday onwards after updating it to September 2019 power bi report server release.

**Comment by liprec** [comment]
To let the HierarchySlicer works in Power BI Report Server you also need to update the Report Server to the latest version.

Thanks, Jan Pieter
