### ISSUE TITLE
Not imporatble to organizational custom visual store

### ISSUE THREAD

**Issue by basbur** [liprec/azurebi-docs#6]
We are using this visual for quite some time. After the organizational custom visual store was released in April, we are changing atm that only visuals from the organizational store can be used.
Because the Hierarchy slicer is using the old Power BI API, it is not uploadable to the organizational store. The error message is: Legacy visuals are not supported. 

Explanation can be found here: https://community.powerbi.com/t5/Service/Issues-with-Microsoft-Visuals-in-Organization-Visual-library/td-p/370770
and here:
https://docs.microsoft.com/en-us/power-bi/power-bi-custom-visuals-organization
under Considerations and limitations (Admin:)

It would be great if you could change the used API for this visual. In your Box and Whisker visual you are already using the new API ;-)

**Comment by liprec** [comment]
I will add this limitation to the documentation to make it more clear.
At this moment the new API is not capable of multilevel slicers.

See liprec/powerbi-hierarchySlicer#32

**Comment by basbur** [comment]
Thank you very much for the fast answer. We will probably take it out of our reports for now and hope that Microsoft will enhance the API for multilevel slicers again.
