### ISSUE TITLE
Hierarchy Slicer  - Tooltip option appears

### ISSUE THREAD

**Issue by FedorKolle** [liprec/azurebi-docs#60]
Hi.
I use the HierarchySlicer  of the latest version and noticed the following:
1) sometimes the included hint option appears in the filter settings, which works. 
After reopening Power BI Desktop, the Tooltip option disappears and there is no tooltip when you hover.
I can’t understand after which the tooltip option appears.
2) when a scroll appears in the HierarchySlicer, the font of the values becomes blurry.
3) the font color on the web and Power BI Desktop is different.
Thank.
![filter bugs](https://user-images.githubusercontent.com/56161510/66214114-c9cd4a00-e6c9-11e9-83c0-ad9ad30d34a6.png)

**Comment by liprec** [comment]
The tooltip is a new feature, but the latest version has been replaced by an older version as there were issues with Internet Explorer.
A new version is being released in a couple of weeks.

**Comment by FedorKolle** [comment]
Hi.
Thank you very much.
When the "Select All" option is enabled, then multi-selection and search do not work.
![image](https://user-images.githubusercontent.com/56161510/66659730-b0d61300-ec4c-11e9-98a1-7ae72d971d64.png)

Also, when selecting and removing items from different groups, **other items are selected**.
We select the months of February, June, April and May.
When we remove the month May, then May is not removed and the elements February and March themselves are selected (although February and March were not selected earlier).
After trying to remove May, February and March appear.
![image](https://user-images.githubusercontent.com/56161510/66662403-6a36e780-ec51-11e9-8f40-7a1994886c8a.png)

Thanks.

**Comment by FedorKolle** [comment]
Hi
WEB Chrome:  appeared **tooltip** and **blur text filter ** when scrolling.
Power BI Desktop: no tooltip and settings.
by default you need to **turn off** the tooltip.
![image](https://user-images.githubusercontent.com/56161510/67270958-56e21280-f4c2-11e9-9aa9-21f97c61b261.png)
Thanks.

**Comment by FedorKolle** [comment]
Hi
Power BI Version: 2.74.5619.621 64-bit (October 2019)
I downloaded a new version of the filter from the store, but the filter does not work when you add it to a new report!
![image](https://user-images.githubusercontent.com/56161510/67271403-1afb7d00-f4c3-11e9-88be-4ca554d1c029.png)
Thanks

**Comment by liprec** [comment]
Accidentally a wrong version of the HierarchySlicer has been released by Microsoft which is causing this behavior, but now the correct working version is available again.

**Comment by FedorKolle** [comment]
thank.
now there is no tooltip and text blur.

**Comment by FedorKolle** [comment]
Hi
Again, appeared tooltip and *blur text filter* when scrolling.
By default you need to turn off the tooltip.
Control is updated from the store itself?
![image](https://user-images.githubusercontent.com/56161510/68369452-68c2e700-014b-11ea-8aec-a2620c2efd87.png)
Thanks

**Comment by liprec** [comment]
Unfortunately it is not possible to disable the tooltips by default, but you can of course disable them from the formatting pane.
And the blurry text are related somehow to Power BI as the visual is not rendering the text as blurry.

-JP

**Comment by FedorKolle** [comment]
Hi.
I noticed today a problem with displaying the selected filter element (and in old reports that have not changed for a long time).
When the filter is synchronized to another page, the display of the selected element does not work on other pages (visually all elements are not selected), although the filter is applied.
Page 1, April selected.
Page 2, visually not visible April, but the filter applied (filter synchronized).
![image](https://user-images.githubusercontent.com/56161510/73924466-9bf94b80-48dd-11ea-9e71-ec4cff8c7a76.png)

Thanks

**Comment by AlekseyPiyadin** [comment]
I confirm the issue ib previous comment.
It's reproduced after publishing in web Power BI service.
Could you resolve this as soon as possible, please.
This is the only slicer which is supporting hierarchy in a good looking way.

Thank you!
