### ISSUE TITLE
Cannot uncheck not top level if 'Select all' is checked

### ISSUE THREAD

**Issue by alina-ivchenko** [liprec/azurebi-docs#61]
If I create a hierarchy slicer with few levels (3 in my case), check 'Select All' and try to uncheck an item not at the top level (for example, on the second), the slicer **doesn't affect charts** and the loading icon indefinitely displays on the slicer.

![image](https://user-images.githubusercontent.com/31377902/66309173-9aa91980-e911-11e9-871c-3c05744f5570.png)
 Actually, there are some items on the third level under Mexico, but opening arrow is disappeared after uncheck.

This issue is reproduced for a SQL Server Analysis Services database (connect live) and an Excel file connection (I haven't checked for other sources).

I have also tried to recreate the slicer and remove it from the report and import from marketplace again, but it haven't helped.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Sorry, but I know that the current version has issues with the Select All option. And a new version will be available in a week or two with a fix for the select all option.

**Comment by liprec** [comment]
Solved with the latest v2.1.3 release
