### ISSUE TITLE
Search function Hierarchy Slicer

### ISSUE THREAD

**Issue by MB333** [liprec/azurebi-docs#63]
Hi Jan,

we are using your slicer quite often and are very happy with it. Unfortunately we have encountered an issue. The search function of your Hierarchy Slicer is not working, when 'select all' is enabled. For several projects we would need 'select all' and the search function.

Thanks in advance.
Dr. Marina Bechtle

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @MB333 ,

Is this still an issues as the latest version has multiple fixes related to the search option.

Thanks, JP
