### ISSUE TITLE
Ordering of categories

### ISSUE THREAD

**Issue by tamarnovetsky** [liprec/azurebi-docs#64]
Is it possible to change the order of the categories on the x-axis? Currently, they seem to be randomly ordered, and I would like to order them alphabetically by category name.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=4555c56c-3a13-42d3-a4d4-df34d7b4e455
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/box-and-whisker-chart.html

**Comment by liprec** [comment]
You can order categories the same way as other visuals via the little menu at the top right of the visual. If you press the tree dots there will be a menu with sorting option available: https://docs.microsoft.com/en-us/power-bi/consumer/end-user-change-sort

An other option of you need some 'special' sorting, like the name of the months, please look at the 'Sort By Column' option in Power BI Desktop: https://docs.microsoft.com/en-us/power-bi/desktop-sort-by-column
