### ISSUE TITLE
HierarchySlicer - Scroll issue when we use Search filter

### ISSUE THREAD

**Issue by RaviTejaBalla-Parker** [liprec/azurebi-docs#66]
When we have a more than 1000 records and filter the list using Search.
Shows list of all filtered data.
But when expanding each list. we observed list moves beyond height of slicer and not able to scroll.
![Capture](https://user-images.githubusercontent.com/56574336/68392782-93835e80-0190-11ea-8af3-76630a1da975.JPG)

**Comment by liprec** [comment]
With the latest version this should not be the case.
Do you see this behavior at the Power BI Service (powerbi.com)?

**Comment by RaviTejaBalla-Parker** [comment]
We are using latest 2.0.22 version.
We observed in 'PowerBI Desktop', Service and Embedded.

**Comment by liprec** [comment]
Is this still an issue as I cannot reproduce it with the current available version?
