### ISSUE TITLE
Selection visibly "disappears" but filter is active 

### ISSUE THREAD

**Issue by puggaard** [liprec/azurebi-docs#67]
We been using Hierarchyslicer for some months now to great satisfaction of the users. Recently it has started behaving differently - seems like when we do a selection, the check box "unchecks" itself, but the filter is still applied. I can submit a video if you would like.

br
Peter

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by PaoloRavina** [comment]
I am also experiencing this. Our hierarchy slicer had the "Apply" button enabled. By disabling the Apply button, we are able to temporarily get around the issue. 

That being said, this functionality is necessary to speed up the day to day use of our model, it would be greatly appreciated if we could get our "Apply" button functionality back!

File --> Options and Settings --> Options --> Query Reduction --> Slicers section

**Comment by zoleitschuk** [comment]
Same issue here as above. Changing Query Reduction--> Slicers selection helped, but doesn't feel like it will work past the short term.

Cheers!

**Comment by liprec** [comment]
Are you using multi select in combination with 'ragged' hierarchies?
This is an issue and a fix is on its way, but I do not have an ETA yet.

-JP

**Comment by puggaard** [comment]
you might be right about the "'ragged' hierarchies" ... I did a change to a "simpler"hierarchy and then it works. Looking very much forward to the fix though. Thanks for your great work!!! 👍👏

**Comment by zeverton** [comment]
I am having this issue on the Power BI service only. If I select more than two items on multi-select, all the checks disappear from the boxes (though the filter stays active) and then if I select any other options it removes the prior filter and starts like nothing else was already selected. This is currently disabling a very key functionality for me. :(

**Comment by liprec** [comment]
A fix will be released somewhere it the next weeks that will fix the issue with multi select and the 'Hide Members' option.

**Comment by musicbydannyd** [comment]
@liprec, I am having the exact same issue as @zeverton and if it helps, my case seems to only involve a DATE hierarchy (Years & Months)... string fields appear to be working as they should. Thank you!

**Comment by musicbydannyd** [comment]
Disregard my last comment... just heard from a colleague who experienced the issue using text fields.

Any update?

Thank you.

**Comment by liprec** [comment]
Just a quick update: currently there are two issues:
- multi-select on different levels are not working with 'ragged' hierarchies => currently working on a new version that contains a fix
- multi-selecting more that two items and disappearing selection => currently investigating what is causing this issue.

Sorry for inconvenience.

**Comment by musicbydannyd** [comment]
Appreciate the quick reply.

**Comment by dillonlopez13** [comment]
When the multi-selecting more than two items bug is fixed, how and when will I know and how can I get it fixed for dashboards?

**Comment by dillonlopez13** [comment]
any update?

**Comment by dillonlopez13** [comment]
@liprec any news on this problem?

**Comment by musicbydannyd** [comment]
FWIW, Microsoft plans to implement their own version in May: https://docs.microsoft.com/en-us/power-platform-release-plan/2020wave1/business-intelligence/hierarchy-slicer

**Comment by TheCapGuy** [comment]
> * multi-selecting more that two items and disappearing selection => currently investigating what is causing this issue.
> 
> Sorry for inconvenience.

Hi, we are experiencing (sort of) the same problem, but the other way around. We have made a central filter page which is bookmarked with all filters in the slicer selected. When users open the report and change it to a few selections and then leave the report open (but not use it), when they go back to the filter page, all filter boxes are selected. Even though the data is showing them values still based on their own selection.

So in my mind, after some time, the slicer shows the default setting of the bookmark (without affecting the data the report is showing.

Does that make sense? (If not related, please let me know. I will address this in a new item)

**Comment by liprec** [comment]
Solved with the latest v2.1.3 release

**Comment by gnanos** [comment]
I am loving the slicer so far! Only have run into one functional issue: 

I have found a similar issue to this where selection visibly disappear but the filter still applies. This happens when another visualization (graph or table) is clicked on. I am currently using v2.2.2. This is not an issue that happens with the default power BI slicer. 

If you need a video of it I can provide that.

Thanks
