### ISSUE TITLE
Multi-select issue when leaves are empty

### ISSUE THREAD

**Issue by Koganti-abhi** [liprec/azurebi-docs#68]
When different levels are multi-selected on the slicer, data doesn't filter or aggregate correctly.
Issue can be reproduced in the attached PBIX file by selecting Hydrogen One (Level 2) and S10+ (Level 3) in the slicer. Rename the file from .txt to .pbix after downloading.

[HierarchySlicerMultiSelectIssue.txt](https://github.com/liprec/azurebi-docs/files/3847836/HierarchySlicerMultiSelectIssue.txt)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @Koganti-abhi ,

Thanks for the feedback and indeed there is an error when you use multi select and have the 'Empty members' enabled. There is a fix coming in a few weeks.

-JP

**Comment by Koganti-abhi** [comment]
Thanks for the update @liprec. Is there any estimated date for the fix?

**Comment by liprec** [comment]
v

**Comment by liprec** [comment]
Solved with the latest v2.1.3 release
