### ISSUE TITLE
Drill through with slicer

### ISSUE THREAD

**Issue by er1ca2000** [liprec/azurebi-docs#69]
I have this slicer on a page that is accepting drill through. When you first land on the page from the previous page, the info isn't showing up. YOu have to click and reclick the slicer. It's like the page is keeping the info that the slicer had before. I have all the settings set to not keep any filters, but it is still doing it. I do not know if this is my error or not. Please let me know. Thank you

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Thanks for your feedback and can you remove the slicer and recreate it again and try again?

Thanks, Jan Pieter
