### ISSUE TITLE
Is the following error from the Boxandwhiskers chart custom visual, or Power BI Desktop?

### ISSUE THREAD

**Issue by maquayle** [liprec/azurebi-docs#71]
Is the following error from the Boxandwhiskers chart custom visual, or Power BI Desktop?
Error: System.InvalidOperationException: Could not execute method: addCustomVisualToPbix(210, {“id”:33925190,”type”:0,”name”:”BoxWhiskerChart …. 500k later….    “:”BoxWhiskerChart1455240051538.pbiviz.json”}],”reportId”:3598428}) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> 

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path ‘items[0].content’, line 1, position 185.
at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)

   at Newtonsoft.Json.JsonTextReader.ReadAsString()

   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)

   at  ..............

Is there a file missing?

Maryann Quayle maquayle@hotmail.com 
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=0bf7dd81-9eed-4035-a928-c3afe7c31e2d
* document_url=https://azurebi-docs.jppp.org/vscode-extensions/pbiviz-cli.html

**Comment by liprec** [comment]
I have seen this problem, but not recently. Is it still an issue with the latest version of Power BI desktop?

**Comment by maquayle** [comment]
Yes. I have Dec 2019 installed.  Is there a fix?

**Comment by liprec** [comment]
Can you try removing the custom visual and re-add it again? For me it fixed the error.
