### ISSUE TITLE
Enabling Search hides last value

### ISSUE THREAD

**Issue by kamalk-github** [liprec/azurebi-docs#72]
If a scrollbar is present in the visual, and we enable Search Bar for this visual, then the last value in the visual cannot be scrolled to.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
This will be fixed in the next version.
Thanks, JP

**Comment by palavi** [comment]
I am also facing this issue. May I ask, when is the next release?. Thanks.

**Comment by liprec** [comment]
Still work in progress. Ad it is a widely used visual, we are taking the time to make sure that a new version doesn't break anything.

**Comment by liprec** [comment]
Solved with the latest v2.1.3 release
