### ISSUE TITLE
Hierarchy  Slicer is completely blank in chrome

### ISSUE THREAD

**Issue by mfuribondo** [liprec/azurebi-docs#73]
The slicer looks fine in the  PBI desktop editor, however once published it is completely blank when viewing in Chrome.  It does work in IE however.
i see this error in the browser console which may be related:

AI: StringValueTooLong message:"string value is too long. It has been truncated to 1024 characters." props:"{value:Error: Blocked a frame with origin \https://app.powerbi.com.us.cas.ms\ from accessing a cross-origin frame.\n    at HTMLDivElement.<anonymous> (https://mcasproxy.azureedge.net/proxyweb/0.162.33/js/js-wrapper.js:12:5189)\n    at https://mcasproxy.azureedge.net/proxyweb/0.162.33/js/js-wrapper.js:8:25122\n    at HTMLDivElement.<anonymous> (https://app.powerbi.com.us.cas.ms/13.0.11674.244/scripts/powerbiportal.dependencies.externals.bundle.min.js?McasJWV=v24:5604:33)\n    at ua (https://app.powerbi.com.us.cas.ms/13.0.11674.244/scripts/powerbiportal.dependencies.externals.bundle.min.js?McasJWV=v24:5544:80)\n    at n.fn.init.append (https://app.powerbi.com.us.cas.ms/13.0.11674.244/scripts/powerbiportal.dependencies.externals.bundle.min.js?McasJWV=v24:5601:9)\n    at o.initContainer (https://app.powerbi.com.us.cas.ms/13.0.11674.244/scripts/powerbiportal.common.bundle.min.js?McasJWV=v24:39523:26)\n    at https://app.powerbi.com.us.cas.ms/13.0.11674.244/scripts/powerbiportal.common.bundle.min.js?McasJWV=v24:39492:55\n    at t}"

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=2380fb48-08d2-44bc-aaa2-2decb8eeed18
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/index.html

**Comment by liprec** [comment]
Hi, is this still an issue?

**Comment by BeKunzy** [comment]
Yes, still an issue for me too!
