### ISSUE TITLE
I can't able to select multiple selections when Hide members set to parent name ( I want to hide parent name)

### ISSUE THREAD

**Issue by vinayak009** [liprec/azurebi-docs#74]
*Start issue here*

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
Duplicate of #68
