### ISSUE TITLE
Hierarchy Slicer - Not syncing

### ISSUE THREAD

**Issue by palavi** [liprec/azurebi-docs#75]
This is a major slicer in our reports. But the slicers are not syncing between the pages when all the items are selected. It would be really helpful if this can be fixed quickly.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
'Select All' isn't a select status: is it only a visual indication and it creates an empty filter and that filter is synced via synced slicers.
At this moment there is no solution to sync the 'select all' status.
