### ISSUE TITLE
Year change auto selects values 

### ISSUE THREAD

**Issue by palavi** [liprec/azurebi-docs#76]
This is on of the major slicer in our reports. We have 2 filters where a parent filter (regular slicer) drives a Year change in Hierarchy slicer, when parent filter changes the hierarchy slicer was unchecked and user has to select a year manually. Now, when we are at the beginning of new year we noticed that when year changes like this Hierarchy slicer is auto selected but data is not filtered until the value is checked manually again. Please help. Thanks

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by liprec** [comment]
Can you share a pbix file with me via mail@datascenarios.nl?

**Comment by palavi** [comment]
[sample Slicer issue.zip](https://github.com/liprec/azurebi-docs/files/4057722/sample.Slicer.issue.zip)

Hi,
I have attached a sample slicer, please choose the Mainly slicer between "Daily" and "Monthly" to see this issue. Sales value disappears even when slicer shows right selection. Thanks.

**Comment by palavi** [comment]
Hi,
Hoping that you received the sample pbix. Did you get a chance to look into this and help us on the same? Thanks.

**Comment by liprec** [comment]
Hi @palavi,

I have looked at your issue and I see the problem, but unfortunately this is something I cannot do anything about it as the slicer is filtered by the selection of your Daily/Monthly slicer.
The only 'solution' is to instruct your users that they have to reselect the correct day to see the results.

-JP
