### ISSUE TITLE
HierarchySlicer

### ISSUE THREAD

**Issue by mibrahim1976** [liprec/azurebi-docs#77]
⚠ Please use the links on the bottom of the [documentation pages](https://azurebi-docs.jppp.org) to get a link between an issue and the page. ⚠Hi, I tried to use HierarchySlicer via Power BI through DAX but unfortunately it doesn't work as i was expecting and i need help on that. Thanks Mohamed

**Comment by liprec** [comment]
Sorry, but can you restate your problem? I cannot extract it from the current context.

**Comment by mibrahim1976** [comment]
Hi Iiprec, i have created path to filter the user by line manger, them i used HierarchySlicer to display the user based on the line manger, when i select specific manger, the list of the user display correctly on HierarchySlicer but in Matrix view shown incorrect users which means the filter it doesn't work properly when i choose specific manager, if you don't mind we can setup a remote session could help, what do you think?

**Comment by mibrahim1976** [comment]
Hi Liprec,

hope you're doing well! i am still waiting your resonance, can i ask you to update me on my above query.

**Comment by mibrahim1976** [comment]
Hi,
do we have any status update?

**Comment by mibrahim1976** [comment]
@liprec ,do we have any status update on this?

**Comment by liprec** [comment]
Sorry, but is it possible to share a Power BI file with me? You can send it to mail@datascenarios.nl

**Comment by mibrahim1976** [comment]
Hi jan,

Thanks for your email, as requested I have create a test file “Test-Hierarchy.pbix” and I have uploaded.

In my test example if you select the VP person on the organization which is Jing Wu it will display all users in Matrix table instead of displaying  the manger and user who reporting to this manger for instance will be Jing Wu as manager and Andre Davico Schneiter since he is reporting directly to Jing as what is shown in the below screenshot.

But since Level 5 and Level 6 doesn’t have more users who are reporting to same manager’s position this why the list is displaying correctly but in other level is mixing the user based on the manager’s position.

Hope my below two examples could help you for the investigation and provide me a solution to fix my dashboard.

VP selection:
[cid:image001.png@01D5D697.CC5E8550]

Level 5 and 6:

[cid:image002.png@01D5D697.CC5E8550]

Thanks
Please help us by creating a ticket or look into the knowledgebase !
https://cofcointernational.service-now.com<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcofcointernational.service-now.com%2F&data=02%7C01%7CMohamedAbdelrahman%40cofcointernational.com%7C1c2d8a6767174f24aed708d709fae399%7C01c999f0c6f347dc92cf4f2d06feda2c%7C0%7C0%7C636988845468846433&sdata=7TMQVOTCOOdydls0E4cNQruRkkCldbiB8N4PoamB6pY%3D&reserved=0>

Mohamed Abdelrahman
IT Senior Engineer
Direct line: +41225286774
Mobile : +41 79 262 3744
Route de Malagnou 101-105, 1224 Chêne-Bougeries, Switzerland
mohamedabdelrahman@cofcointernational.com<mailto:mohamedabdelrahman@cofcointernational.com>

      [cid:image001.png@01D2A949.B7C87480]
      www.cofcointernational.com<http://www.cofcointernational.com/>

**Comment by mibrahim1976** [comment]
@liprec ,do we have any status update on this?

**Comment by liprec** [comment]
Sorry, I missed that I didn't responded yet.
But a selecting a member in the HierarchySlicer always includes its children, so if you select the VP, it will include all persons that (in)directly report to them.
There is no option to restrict the selection to only direct reports.

-JP

**Comment by mibrahim1976** [comment]
@liprec, thanks for the feedback, is there any workaround to segregate this children from and fetch only the direct report?
