### ISSUE TITLE
HierarchySlicer: Allow Changes for Scroll Bar Color

### ISSUE THREAD

**Issue by donnitazen** [liprec/azurebi-docs#80]
*Start issue here*
Hi, 

We are wondering whether the scroll bar colour could be modified. The scroll bar has transparent dark grey colour. As we have been using black background and it seems many people don't realise that the slicer is scrollable. 

![image](https://user-images.githubusercontent.com/10163996/72572356-33d4cc80-3912-11ea-9b71-a4fc122a0a62.png)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Thanks for the suggestion and it will be included in teh next release.
