### ISSUE TITLE
Last Member not shown

### ISSUE THREAD

**Issue by MartinF274** [liprec/azurebi-docs#82]
I have one issue with the slicer. In case there are so many members that the scroll bar is activated and at the same time the search option is enabled I have the issue that the last member of my hierarchy is no more shown within the slicer.

Best regards,
Martin

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
This is indeed a bug and will be fixed in the next version. Currently I do not have an ETA for the release yet.
-JP
