### ISSUE TITLE
Hierarchy Slicer goes 'blank' when selecting multiple values

### ISSUE THREAD

**Issue by BeKunzy** [liprec/azurebi-docs#83]
I'm experiencing the same issue as a number of users who have commented under the 'reviews' section of the app store.

**The slicer is not working if we select more than 2 values at parent level**
Hi, With the December update of Power BI, the hierarchy slicer does not show the selected values if we select more than two items at parent level. It just gets blank.

**Slicer gets blank when selecting multiple values**
For the last two months the slicer has been having some issues. When selecting multiple values the slicer gets blank, like if there was nothing selected. This is causing misinterpretations and I feel forced to change all the HierarchySlicers to the default slicer.

...I've got nothing to add on top of this, other than to share that I'm also frustrated by it!
Any idea of a timeline for a fix?

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by matjeh** [comment]
Having the same issue

**Comment by liprec** [comment]
There is an issue with slicer selections and my slicer.
I am currently looking into it together with Microsoft to identify what is going wrong.

-JP

**Comment by NicBur** [comment]
The slicer does work if 3+ values are selected, the problem is that all values selected disappear and so the user will understandably either be confused, frustrated or give misleading information.

If you export the chart or table created by those filters, then the filters applied appear (correctly) in the first row in the export.  But again that is not a good user experience.

**Comment by NicBur** [comment]
It would be really good to know if this is going to be fixed
