### ISSUE TITLE
Default slicer selection in Power BI Desktop not retained after publishing

### ISSUE THREAD

**Issue by mostvp278** [liprec/azurebi-docs#84]
The hierarchy slicer is a great tool to better visualise Quarter/Month parent-child hierarchies. However, when I select a default value for the slicer in Power BI Desktop and then publish the report, on the online version the default slicer selection is not retained. I am using "Lock aspect", and my Microsoft non-hierarchy slicers are working fine. 

In Power BI desktop:
![image](https://user-images.githubusercontent.com/60695343/73838880-9a138780-480c-11ea-845f-13aaf44a43a2.png)

In Power BI online service after publishing:
![image](https://user-images.githubusercontent.com/60695343/73838935-bb747380-480c-11ea-9d0e-4c765a850002.png)

Is this normal behavior? Shouldn't the default selected value be conserved like with a normal slicer?
Thank you for your help :)
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
This is definitely not the default behavior, but somehow things are going wrong while processing the stored filters. I am investigating what is causing this.

-JP

**Comment by Mike-Honey** [comment]
I'm seeing similar behaviour, but for a single-select scenario.

**Comment by mostvp278** [comment]
Thanks for your reply @liprec. Glad to hear that this isn't the default behavior! 
Unfortunately I am still having the issue mentioned. For me no slicer selection is being conserved, whether in a single select or multi select scenario @Mike-Honey, oddly enough. Any idea when there will be a fix? Many thanks!

**Comment by atapia197** [comment]
Hi all and thank @liprec for your reply.
In my case, the filter doesn´t sincronize with other panels of the same web report, although it works ok on the Desktop version.

**Comment by Yigalco** [comment]
Having the same issue

**Comment by mivisk** [comment]
I can confirm same behaviour. Works in desktop and is not working properly in service. In addition filters are actually working and retaining selection also in service , just there is no visible indication of selection. I tried to documented it also here: https://community.powerbi.com/t5/Issues/Hierarchy-slicer-is-not-syncing-in-service-syncing-is-working-in/idc-p/932492
Strangely enough same behaviour is in mobile iOs app (filtering works, just no visual indication).

**Comment by liprec** [comment]
There is an issue with slicer selections and my slicer.
I am currently looking into it together with Microsoft to identify what is going wrong.

-JP

**Comment by atapia197** [comment]
Hi @liprec ,
I have an issue with the Hierarchy Slicer in the PowerBI web version (not in desktop).
When I select a 1st level filter, it syncs with other pages of the report, and shows the active filter.
On the other hand, if I select a 2nd level filter, it syncs with other pages of the report, but doesn´t show the active filter.
Attached you will see a caption to understand my message (I hope it helps :)
![visual-powerbi](https://user-images.githubusercontent.com/61007601/74773105-86970080-5291-11ea-8744-221f77ad2762.gif)

**Comment by slkastner** [comment]
This issue does not appear to be fixed. @liprec have you been able to verify that this error still exists with Microsoft? Any progress on a planned fix?
I am running -

![image](https://user-images.githubusercontent.com/82608087/114917477-9b1a4e80-9deb-11eb-82b4-9f9f64424458.png)

**Comment by liprec** [comment]
Currently I am not known with any issue related to this and the original issues has been fixed. Are you currently experiencing this issue?
