### ISSUE TITLE
use the control offline 

### ISSUE THREAD

**Issue by iyadhh** [liprec/azurebi-docs#85]
Hi,
i'm using this awesome control usually on PCs with internet connection,
however i'm facing issue when try to use it on PCs without internet connection, the control took long time to render apparently due to wait response from online calls to this 
Request URL: https://visuals.azureedge.net/prod/approvedResources.json
on the other hand many environments tend to block this call and the visual kept showing no data till the response back or got cancelled,
is there any way to workaround this?

Regards.

**Comment by liprec** [comment]
This is standard behavior of Power BI desktop and it is part of the automatic update process of custom visuals. Unfortunately I cannot do anything about it as it is part of Power BI desktop itself.

-JP

**Comment by iyadhh** [comment]
Thanks for reply, i understand we can live with that.

however i have one more observation which is totally unclear,
i configure power BI with custom authentication to meet our business "every thing working just fine"
however on PCs that has internet connection and after allowing the traffic from this URL https://visuals.azureedge.net/prod/approvedResources.json
now the visual is rendering immediately and its title appeared but without data!, if back to default authentication the visual works just fine, any clue where to look into this issue?

**Comment by iyadhh** [comment]
Hi,
So apparently and upon applying custom security with Power BI Report Server
Standard visuals are running but not this visual,
I see below error when click F12

Can you help, please. Thank you
![network](https://user-images.githubusercontent.com/775167/74593844-a8e60f80-5040-11ea-952c-6386491660e6.PNG)

![detail](https://user-images.githubusercontent.com/775167/74593853-ca46fb80-5040-11ea-85d9-903bb2cf0e3a.PNG)
