### ISSUE TITLE
Slicer selection disappears in web-version after publishing

### ISSUE THREAD

**Issue by AlekseyPiyadin** [liprec/azurebi-docs#86]
I have two tabs in dashboard with synchronized slicer. Multiselect option is on. There are 3 levels of hierarchy in the slicer.
When I filter something on first tab and go to the second one, the slicer checkboxes are all off (not selected), but filter has  applied for the visuals.

This behaviour is only in web-version after publishing, which is used by all business users of my dashboard.
In desktop version of Power BI slicer is working properly.

Could you fix this issue, please.

**Comment by AlekseyPiyadin** [comment]
Does anybody here?
There have been reported many similar issues, and there is no answer until now.
We need a support, please.
How to fix problem at the moment, whithout waiting till May, 2020 when HierarchySlicer will be released oficially as part of native visuals of Power BI.

**Comment by liprec** [comment]
There is a general issue with the sync slicer option in combination with my slicer. I am currently looking into it together with Microsoft to identify what is going wrong.

-JP
