### ISSUE TITLE
WHEN CLICKING SOME FILTER ELEMENTS IN CHECK BOX, OTHER CHECKBOXS MARKERS DISAPPEAR

### ISSUE THREAD

**Issue by Yigalco** [liprec/azurebi-docs#89]
the checkbox "unchecks" itself, but the filter is still applied
BR,
Yigal

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @Yigalco,

Sorry for the late response, can you validate if this issue is still there as there should be a fix released that fixes this issue

**Comment by Yigalco** [comment]
Hi,
I download the last version again and update the visual and it same.
Your site says that the latest version 2.0.23 and in PBI i see 2.0.22 (Attached pic)

![VHS_Version](https://user-images.githubusercontent.com/61044237/81048066-49233600-8ec4-11ea-8124-1d6842df3fe4.png)

**Comment by Yigalco** [comment]
Hi,
I download the last version again and update the visual and it same.
Your site says that the latest version 2.0.23 and in PBI i see 2.0.22
(Attached pic)

BRת
Yigal
[image: VHS_Version.png]

**Comment by liprec** [comment]
It is true that the version in AppSource is one off with the production version; currently 2.0.22 is the latest version.
Regarding your question: are you using the HierarchySlicer with Power BI Report Server? If so, please update to the latest (patch) version as there had been issues with Power BI and my HierarchySlicer.

-JP

**Comment by oihanemendez** [comment]
Hi,
Same issue here. After selecting all, when we uncheck some items, others are also unchecked. That happens in Power BI Desktop, and in Power BI Service running in Chrome.

Thanks
