### ISSUE TITLE
Hiearchy Slicer Showing Up Blank In Chrome For PowerBI Report Server

### ISSUE THREAD

**Issue by CCLNTN** [liprec/azurebi-docs#93]
The hierarchy slicer is showing up blank in chrome. We are using Power BI Report Server. I have tested this for both the September 2019 and January 2020 versions. It is only impacting certain users on certain machines. For instance I have no problems on my local machine however when I remote into a machine at the office I experience the blank visuals.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @CCLNTN ,

Sorry for the late reaction, but do you have the latest updates of Power BI Report Server installed?
