### ISSUE TITLE
Hierarchy Slicer: Scroll down issue

### ISSUE THREAD

**Issue by everisAMS** [liprec/azurebi-docs#95]
Dears,

 

We have just found a bug when filtering with the HierarchySlicer visualizzation: the scroll bar does not show all results.
You can reproduce this issue with any source data by:
1. Select the HierarchySlicer visualizzazion

2. Add up to 3 hirarchical levels with several values for each level

3. Keep the visualizzation box small

4. Try to scroll down to find any value

 

Can you please check this issue?
We have the temporary workaround by using the search bar, but it is not intuitive.

Many thanks in advance for your help.

Yours faithfully,
Valentina

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @everisAMS,

Thanks for the feedback and the next version will contain a fix for this issue. Currently I do not have an ETA yet, but I am working on the release.

**Comment by liprec** [comment]
Solved with the latest v2.1.3 release

**Comment by abhayjadhav-24** [comment]
Hi, still i can see the scroll bar does not show all results. Currently i am using the Version: 2.1.4
could you please check on this?

**Comment by cyril090** [comment]
Hello I face the same issue, when I scroll down on huge dataset I don't see all results

**Comment by iamonlysaiful** [comment]
Please solve the issue, it's become a headache now.

**Comment by TWWork** [comment]
The issue pop up again. Please can you fix it.
