### ISSUE TITLE
select all items and then deselect items does not work

### ISSUE THREAD

**Issue by nelz75** [liprec/azurebi-docs#96]
When all items are selected and then I try to unselect just one item... waiting a little bit, all item get back selected.
Works fine if no items are selected and then start selecting some, the selection works fine.

Hope you will fix quicly this bug. If you need more details just ask. 

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Thanks for the feedback and the select all logic has changed in the new release and I will check if this scenario is correctly covered.

**Comment by liprec** [comment]
Solved with the latest v2.1.3 release
