### ISSUE TITLE
Erratic random changes of selected items

### ISSUE THREAD

**Issue by lmerhay** [liprec/azurebi-docs#97]
This may be related to #96 

Hi,

the following occurred with version 2.0.22 (this gets installed, however AppSource shows current version is 2.0.23)

...and this happens only when "Hide Members" > "Empty" is selected

1. When all items are selected with Select all, or a branch is selected with the branch level selector, and then a single (sub)item is unchecked from the lowest level of a 3 level hierarchy, all existing selection is cleared
2. when an item is selcted, it gets unselected, then it stays selected on the second try. then, when an additional item is selected, all existing selection gets cleared.

This behaviour applies to all dim tables of the data model.

Interestingly, when the fields are added one by one, independently, and not as a hierarchy, the behaviour of the slicer seems more stable, yet not perfect, more precisely, the first issue persists, while the second does not occur.

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @lmerhay,

Thanks for the feedback and there is an issue with selection of different member levels and 'Hide Members' enabled. This will be fixed in the upcoming version, but unfortunately I do not have an ETA yet.

-JP

**Comment by lmerhay** [comment]
Hi @liprec, thanks for the feedback!

**Comment by liprec** [comment]
Solved with the latest v2.1.3 release
