### ISSUE TITLE
Integrating external D3 libraries in D3 Skeleton

### ISSUE THREAD

**Issue by julmoser** [liprec/azurebi-docs#98]
Hi I am trying to integrate a Gantt Chart D3 Code into your Skeleton (e.g. using the [Gantt library](https://github.com/dk8996/Gantt-Chart), however this always results in a blank visual.
Is the Skeleton limited to rendering D3 Visuals that are built from scratch within the Skeleton and thus not using external libraries or functions like in the example above? Or can external libraries be integrated somehow?

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=59bc6305-3908-4afa-bdfd-66ed39c91192
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/d3js.html

**Comment by nowherenearithaca** [comment]
Same question
