### ISSUE TITLE
Box and whisker saying too many values in sampling field

### ISSUE THREAD

**Issue by Giridhar327** [liprec/azurebi-docs#99]
*Start issue here*
Box and whisker chart is showing the warning.. Too many values in sampling.not showing all data... Filter the data.. This scenario observed for some of the users.. What is limitation of data.. Is there any way to increase the data limitations.. 

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=4555c56c-3a13-42d3-a4d4-df34d7b4e455
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/box-and-whisker-chart.html

**Comment by liprec** [comment]
Hi @Giridhar327,

There is a limitation of the amount of data that can be loaded by the visual and it is a limitation of custom visuals in general, but it is not fixed.
I have seen that it is capable of loading up to 120.000 data points, but it is dependent of the type of data.
If you hover above a box you will see the tooltip which contains the amount of data points.

Thanks, JP

**Comment by Giridhar327** [comment]
Thanks Jan Pieter for the reply.

one more issue in box and whisker chart.

We have option for tooltip.But when I added any measure it tooltip info is not coming.
Can you Please look into it.

When i hovered on each box also i am not getting tooltip value.
Is there any way to see the ToolTip

![Capture](https://user-images.githubusercontent.com/64241326/80606210-ac8b0f00-8a51-11ea-9ebb-06c0747ac941.PNG)
